!function(b){"function"==typeof define&&define.amd?define(["jquery"],b):"undefined"!=typeof exports?module.exports=b(require("jquery")):b(jQuery)}(function(b){var c=window.Slick||{},h=0;(c=function(a,d){var g;this.defaults={accessibility:!0,adaptiveHeight:!1,appendArrows:b(a),appendDots:b(a),arrows:!0,asNavFor:null,prevArrow:'\x3cbutton class\x3d"slick-prev" aria-label\x3d"Previous" type\x3d"button"\x3ePrevious\x3c/button\x3e',nextArrow:'\x3cbutton class\x3d"slick-next" aria-label\x3d"Next" type\x3d"button"\x3eNext\x3c/button\x3e',
autoplay:!1,autoplaySpeed:3E3,centerMode:!1,centerPadding:"50px",cssEase:"ease",customPaging:function(a,d){return b('\x3cbutton type\x3d"button" /\x3e').text(d+1)},dots:!1,dotsClass:"slick-dots",draggable:!0,easing:"linear",edgeFriction:0.35,fade:!1,focusOnSelect:!1,focusOnChange:!1,infinite:!0,initialSlide:0,lazyLoad:"ondemand",mobileFirst:!1,pauseOnHover:!0,pauseOnFocus:!0,pauseOnDotsHover:!1,respondTo:"window",responsive:null,rows:1,rtl:!1,slide:"",slidesPerRow:1,slidesToShow:1,slidesToScroll:1,
speed:500,swipe:!0,swipeToSlide:!1,touchMove:!0,touchThreshold:5,useCSS:!0,useTransform:!0,variableWidth:!1,vertical:!1,verticalSwiping:!1,waitForAnimate:!0,zIndex:1E3};this.initials={animating:!1,dragging:!1,autoPlayTimer:null,currentDirection:0,currentLeft:null,currentSlide:0,direction:1,$dots:null,listWidth:null,listHeight:null,loadIndex:0,$nextArrow:null,$prevArrow:null,scrolling:!1,slideCount:null,slideWidth:null,$slideTrack:null,$slides:null,sliding:!1,slideOffset:0,swipeLeft:null,swiping:!1,
$list:null,touchObject:{},transformsEnabled:!1,unslicked:!1};b.extend(this,this.initials);this.animProp=this.animType=this.activeBreakpoint=null;this.breakpoints=[];this.breakpointSettings=[];this.interrupted=this.focussed=this.cssTransitions=!1;this.hidden="hidden";this.paused=!0;this.respondTo=this.positionProp=null;this.rowCount=1;this.shouldClick=!0;this.$slider=b(a);this.transitionType=this.transformType=this.$slidesCache=null;this.visibilityChange="visibilitychange";this.windowWidth=0;this.windowTimer=
null;g=b(a).data("slick")||{};this.options=b.extend({},this.defaults,d,g);this.currentSlide=this.options.initialSlide;this.originalSettings=this.options;void 0!==document.mozHidden?(this.hidden="mozHidden",this.visibilityChange="mozvisibilitychange"):void 0!==document.webkitHidden&&(this.hidden="webkitHidden",this.visibilityChange="webkitvisibilitychange");this.autoPlay=b.proxy(this.autoPlay,this);this.autoPlayClear=b.proxy(this.autoPlayClear,this);this.autoPlayIterator=b.proxy(this.autoPlayIterator,
this);this.changeSlide=b.proxy(this.changeSlide,this);this.clickHandler=b.proxy(this.clickHandler,this);this.selectHandler=b.proxy(this.selectHandler,this);this.setPosition=b.proxy(this.setPosition,this);this.swipeHandler=b.proxy(this.swipeHandler,this);this.dragHandler=b.proxy(this.dragHandler,this);this.keyHandler=b.proxy(this.keyHandler,this);this.instanceUid=h++;this.htmlExpr=/^(?:\s*(<[\w\W]+>)[^>]*)$/;this.registerBreakpoints();this.init(!0)}).prototype.activateADA=function(){this.$slideTrack.find(".slick-active").attr({"aria-hidden":"false"}).find("a, input, button, select").attr({tabindex:"0"})};
c.prototype.addSlide=c.prototype.slickAdd=function(a,d,g){if("boolean"==typeof d)g=d,d=null;else if(0>d||d>=this.slideCount)return!1;this.unload();"number"==typeof d?0===d&&0===this.$slides.length?b(a).appendTo(this.$slideTrack):g?b(a).insertBefore(this.$slides.eq(d)):b(a).insertAfter(this.$slides.eq(d)):!0===g?b(a).prependTo(this.$slideTrack):b(a).appendTo(this.$slideTrack);this.$slides=this.$slideTrack.children(this.options.slide);this.$slideTrack.children(this.options.slide).detach();this.$slideTrack.append(this.$slides);
this.$slides.each(function(a,d){b(d).attr("data-slick-index",a)});this.$slidesCache=this.$slides;this.reinit()};c.prototype.animateHeight=function(){if(1===this.options.slidesToShow&&!0===this.options.adaptiveHeight&&!1===this.options.vertical){var a=this.$slides.eq(this.currentSlide).outerHeight(!0);this.$list.animate({height:a},this.options.speed)}};c.prototype.animateSlide=function(a,d){var g={},e=this;e.animateHeight();!0===e.options.rtl&&!1===e.options.vertical&&(a=-a);!1===e.transformsEnabled?
!1===e.options.vertical?e.$slideTrack.animate({left:a},e.options.speed,e.options.easing,d):e.$slideTrack.animate({top:a},e.options.speed,e.options.easing,d):!1===e.cssTransitions?(!0===e.options.rtl&&(e.currentLeft=-e.currentLeft),b({animStart:e.currentLeft}).animate({animStart:a},{duration:e.options.speed,easing:e.options.easing,step:function(a){a=Math.ceil(a);!1===e.options.vertical?(g[e.animType]="translate("+a+"px, 0px)",e.$slideTrack.css(g)):(g[e.animType]="translate(0px,"+a+"px)",e.$slideTrack.css(g))},
complete:function(){d&&d.call()}})):(e.applyTransition(),a=Math.ceil(a),!1===e.options.vertical?g[e.animType]="translate3d("+a+"px, 0px, 0px)":g[e.animType]="translate3d(0px,"+a+"px, 0px)",e.$slideTrack.css(g),d&&setTimeout(function(){e.disableTransition();d.call()},e.options.speed))};c.prototype.getNavTarget=function(){var a=this.options.asNavFor;return a&&null!==a&&(a=b(a).not(this.$slider)),a};c.prototype.asNavFor=function(a){var d=this.getNavTarget();null!==d&&"object"==typeof d&&d.each(function(){var d=
b(this).slick("getSlick");d.unslicked||d.slideHandler(a,!0)})};c.prototype.applyTransition=function(a){var d={};!1===this.options.fade?d[this.transitionType]=this.transformType+" "+this.options.speed+"ms "+this.options.cssEase:d[this.transitionType]="opacity "+this.options.speed+"ms "+this.options.cssEase;!1===this.options.fade?this.$slideTrack.css(d):this.$slides.eq(a).css(d)};c.prototype.autoPlay=function(){this.autoPlayClear();this.slideCount>this.options.slidesToShow&&(this.autoPlayTimer=setInterval(this.autoPlayIterator,
this.options.autoplaySpeed))};c.prototype.autoPlayClear=function(){this.autoPlayTimer&&clearInterval(this.autoPlayTimer)};c.prototype.autoPlayIterator=function(){var a=this.currentSlide+this.options.slidesToScroll;this.paused||this.interrupted||this.focussed||(!1===this.options.infinite&&(1===this.direction&&this.currentSlide+1===this.slideCount-1?this.direction=0:0===this.direction&&(a=this.currentSlide-this.options.slidesToScroll,0==this.currentSlide-1&&(this.direction=1))),this.slideHandler(a))};
c.prototype.buildArrows=function(){!0===this.options.arrows&&(this.$prevArrow=b(this.options.prevArrow).addClass("slick-arrow"),this.$nextArrow=b(this.options.nextArrow).addClass("slick-arrow"),this.slideCount>this.options.slidesToShow?(this.$prevArrow.removeClass("slick-hidden").removeAttr("aria-hidden tabindex"),this.$nextArrow.removeClass("slick-hidden").removeAttr("aria-hidden tabindex"),this.htmlExpr.test(this.options.prevArrow)&&this.$prevArrow.prependTo(this.options.appendArrows),this.htmlExpr.test(this.options.nextArrow)&&
this.$nextArrow.appendTo(this.options.appendArrows),!0!==this.options.infinite&&this.$prevArrow.addClass("slick-disabled").attr("aria-disabled","true")):this.$prevArrow.add(this.$nextArrow).addClass("slick-hidden").attr({"aria-disabled":"true",tabindex:"-1"}))};c.prototype.buildDots=function(){var a,d;if(!0===this.options.dots){this.$slider.addClass("slick-dotted");d=b("\x3cul /\x3e").addClass(this.options.dotsClass);for(a=0;a<=this.getDotCount();a+=1)d.append(b("\x3cli /\x3e").append(this.options.customPaging.call(this,
this,a)));this.$dots=d.appendTo(this.options.appendDots);this.$dots.find("li").first().addClass("slick-active")}};c.prototype.buildOut=function(){this.$slides=this.$slider.children(this.options.slide+":not(.slick-cloned)").addClass("slick-slide");this.slideCount=this.$slides.length;this.$slides.each(function(a,d){b(d).attr("data-slick-index",a).data("originalStyling",b(d).attr("style")||"")});this.$slider.addClass("slick-slider");this.$slideTrack=0===this.slideCount?b('\x3cdiv class\x3d"slick-track"/\x3e').appendTo(this.$slider):
this.$slides.wrapAll('\x3cdiv class\x3d"slick-track"/\x3e').parent();this.$list=this.$slideTrack.wrap('\x3cdiv class\x3d"slick-list"/\x3e').parent();this.$slideTrack.css("opacity",0);!0!==this.options.centerMode&&!0!==this.options.swipeToSlide||(this.options.slidesToScroll=1);b("img[data-lazy]",this.$slider).not("[src]").addClass("slick-loading");this.setupInfinite();this.buildArrows();this.buildDots();this.updateDots();this.setSlideClasses("number"==typeof this.currentSlide?this.currentSlide:0);
!0===this.options.draggable&&this.$list.addClass("draggable")};c.prototype.buildRows=function(){var a,d,b,e,f,c,k;if(e=document.createDocumentFragment(),c=this.$slider.children(),1<this.options.rows){k=this.options.slidesPerRow*this.options.rows;f=Math.ceil(c.length/k);for(a=0;a<f;a++){var h=document.createElement("div");for(d=0;d<this.options.rows;d++){var i=document.createElement("div");for(b=0;b<this.options.slidesPerRow;b++){var j=a*k+(d*this.options.slidesPerRow+b);c.get(j)&&i.appendChild(c.get(j))}h.appendChild(i)}e.appendChild(h)}this.$slider.empty().append(e);
this.$slider.children().children().children().css({width:100/this.options.slidesPerRow+"%",display:"inline-block"})}};c.prototype.checkResponsive=function(a,d){var g,e,f,c=!1;e=this.$slider.width();var k=window.innerWidth||b(window).width();if("window"===this.respondTo?f=k:"slider"===this.respondTo?f=e:"min"===this.respondTo&&(f=Math.min(k,e)),this.options.responsive&&this.options.responsive.length&&null!==this.options.responsive){e=null;for(g in this.breakpoints)this.breakpoints.hasOwnProperty(g)&&
(!1===this.originalSettings.mobileFirst?f<this.breakpoints[g]&&(e=this.breakpoints[g]):f>this.breakpoints[g]&&(e=this.breakpoints[g]));null!==e?null!==this.activeBreakpoint?(e!==this.activeBreakpoint||d)&&(this.activeBreakpoint=e,"unslick"===this.breakpointSettings[e]?this.unslick(e):(this.options=b.extend({},this.originalSettings,this.breakpointSettings[e]),!0===a&&(this.currentSlide=this.options.initialSlide),this.refresh(a)),c=e):(this.activeBreakpoint=e,"unslick"===this.breakpointSettings[e]?
this.unslick(e):(this.options=b.extend({},this.originalSettings,this.breakpointSettings[e]),!0===a&&(this.currentSlide=this.options.initialSlide),this.refresh(a)),c=e):null!==this.activeBreakpoint&&(this.activeBreakpoint=null,this.options=this.originalSettings,!0===a&&(this.currentSlide=this.options.initialSlide),this.refresh(a),c=e);a||!1===c||this.$slider.trigger("breakpoint",[this,c])}};c.prototype.changeSlide=function(a,d){var g,e,f;e=b(a.currentTarget);switch(e.is("a")&&a.preventDefault(),e.is("li")||
(e=e.closest("li")),f=0!=this.slideCount%this.options.slidesToScroll,g=f?0:(this.slideCount-this.currentSlide)%this.options.slidesToScroll,a.data.message){case "previous":e=0===g?this.options.slidesToScroll:this.options.slidesToShow-g;this.slideCount>this.options.slidesToShow&&this.slideHandler(this.currentSlide-e,!1,d);break;case "next":e=0===g?this.options.slidesToScroll:g;this.slideCount>this.options.slidesToShow&&this.slideHandler(this.currentSlide+e,!1,d);break;case "index":g=0===a.data.index?
0:a.data.index||e.index()*this.options.slidesToScroll,this.slideHandler(this.checkNavigable(g),!1,d),e.children().trigger("focus")}};c.prototype.checkNavigable=function(a){var d,b;if(d=this.getNavigableIndexes(),b=0,a>d[d.length-1])a=d[d.length-1];else for(var e in d){if(a<d[e]){a=b;break}b=d[e]}return a};c.prototype.cleanUpEvents=function(){this.options.dots&&null!==this.$dots&&(b("li",this.$dots).off("click.slick",this.changeSlide).off("mouseenter.slick",b.proxy(this.interrupt,this,!0)).off("mouseleave.slick",
b.proxy(this.interrupt,this,!1)),!0===this.options.accessibility&&this.$dots.off("keydown.slick",this.keyHandler));this.$slider.off("focus.slick blur.slick");!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&(this.$prevArrow&&this.$prevArrow.off("click.slick",this.changeSlide),this.$nextArrow&&this.$nextArrow.off("click.slick",this.changeSlide),!0===this.options.accessibility&&(this.$prevArrow&&this.$prevArrow.off("keydown.slick",this.keyHandler),this.$nextArrow&&this.$nextArrow.off("keydown.slick",
this.keyHandler)));this.$list.off("touchstart.slick mousedown.slick",this.swipeHandler);this.$list.off("touchmove.slick mousemove.slick",this.swipeHandler);this.$list.off("touchend.slick mouseup.slick",this.swipeHandler);this.$list.off("touchcancel.slick mouseleave.slick",this.swipeHandler);this.$list.off("click.slick",this.clickHandler);b(document).off(this.visibilityChange,this.visibility);this.cleanUpSlideEvents();!0===this.options.accessibility&&this.$list.off("keydown.slick",this.keyHandler);
!0===this.options.focusOnSelect&&b(this.$slideTrack).children().off("click.slick",this.selectHandler);b(window).off("orientationchange.slick.slick-"+this.instanceUid,this.orientationChange);b(window).off("resize.slick.slick-"+this.instanceUid,this.resize);b("[draggable!\x3dtrue]",this.$slideTrack).off("dragstart",this.preventDefault);b(window).off("load.slick.slick-"+this.instanceUid,this.setPosition)};c.prototype.cleanUpSlideEvents=function(){this.$list.off("mouseenter.slick",b.proxy(this.interrupt,
this,!0));this.$list.off("mouseleave.slick",b.proxy(this.interrupt,this,!1))};c.prototype.cleanUpRows=function(){var a;1<this.options.rows&&((a=this.$slides.children().children()).removeAttr("style"),this.$slider.empty().append(a))};c.prototype.clickHandler=function(a){!1===this.shouldClick&&(a.stopImmediatePropagation(),a.stopPropagation(),a.preventDefault())};c.prototype.destroy=function(a){this.autoPlayClear();this.touchObject={};this.cleanUpEvents();b(".slick-cloned",this.$slider).detach();this.$dots&&
this.$dots.remove();this.$prevArrow&&this.$prevArrow.length&&(this.$prevArrow.removeClass("slick-disabled slick-arrow slick-hidden").removeAttr("aria-hidden aria-disabled tabindex").css("display",""),this.htmlExpr.test(this.options.prevArrow)&&this.$prevArrow.remove());this.$nextArrow&&this.$nextArrow.length&&(this.$nextArrow.removeClass("slick-disabled slick-arrow slick-hidden").removeAttr("aria-hidden aria-disabled tabindex").css("display",""),this.htmlExpr.test(this.options.nextArrow)&&this.$nextArrow.remove());
this.$slides&&(this.$slides.removeClass("slick-slide slick-active slick-center slick-visible slick-current").removeAttr("aria-hidden").removeAttr("data-slick-index").each(function(){b(this).attr("style",b(this).data("originalStyling"))}),this.$slideTrack.children(this.options.slide).detach(),this.$slideTrack.detach(),this.$list.detach(),this.$slider.append(this.$slides));this.cleanUpRows();this.$slider.removeClass("slick-slider");this.$slider.removeClass("slick-initialized");this.$slider.removeClass("slick-dotted");
this.unslicked=!0;a||this.$slider.trigger("destroy",[this])};c.prototype.disableTransition=function(a){var d={};d[this.transitionType]="";!1===this.options.fade?this.$slideTrack.css(d):this.$slides.eq(a).css(d)};c.prototype.fadeSlide=function(a,d){var b=this;!1===b.cssTransitions?(b.$slides.eq(a).css({zIndex:b.options.zIndex}),b.$slides.eq(a).animate({opacity:1},b.options.speed,b.options.easing,d)):(b.applyTransition(a),b.$slides.eq(a).css({opacity:1,zIndex:b.options.zIndex}),d&&setTimeout(function(){b.disableTransition(a);
d.call()},b.options.speed))};c.prototype.fadeSlideOut=function(a){!1===this.cssTransitions?this.$slides.eq(a).animate({opacity:0,zIndex:this.options.zIndex-2},this.options.speed,this.options.easing):(this.applyTransition(a),this.$slides.eq(a).css({opacity:0,zIndex:this.options.zIndex-2}))};c.prototype.filterSlides=c.prototype.slickFilter=function(a){null!==a&&(this.$slidesCache=this.$slides,this.unload(),this.$slideTrack.children(this.options.slide).detach(),this.$slidesCache.filter(a).appendTo(this.$slideTrack),
this.reinit())};c.prototype.focusHandler=function(){var a=this;a.$slider.off("focus.slick blur.slick").on("focus.slick blur.slick","*",function(d){d.stopImmediatePropagation();var g=b(this);setTimeout(function(){a.options.pauseOnFocus&&(a.focussed=g.is(":focus"),a.autoPlay())},0)})};c.prototype.getCurrent=c.prototype.slickCurrentSlide=function(){return this.currentSlide};c.prototype.getDotCount=function(){var a=0,d=0,b=0;if(!0===this.options.infinite)if(this.slideCount<=this.options.slidesToShow)++b;
else for(;a<this.slideCount;)++b,a=d+this.options.slidesToScroll,d+=this.options.slidesToScroll<=this.options.slidesToShow?this.options.slidesToScroll:this.options.slidesToShow;else if(!0===this.options.centerMode)b=this.slideCount;else if(this.options.asNavFor)for(;a<this.slideCount;)++b,a=d+this.options.slidesToScroll,d+=this.options.slidesToScroll<=this.options.slidesToShow?this.options.slidesToScroll:this.options.slidesToShow;else b=1+Math.ceil((this.slideCount-this.options.slidesToShow)/this.options.slidesToScroll);
return b-1};c.prototype.getLeft=function(a){var d,b,e,f,c=0;return this.slideOffset=0,b=this.$slides.first().outerHeight(!0),!0===this.options.infinite?(this.slideCount>this.options.slidesToShow&&(this.slideOffset=-1*this.slideWidth*this.options.slidesToShow,f=-1,!0===this.options.vertical&&!0===this.options.centerMode&&(2===this.options.slidesToShow?f=-1.5:1===this.options.slidesToShow&&(f=-2)),c=b*this.options.slidesToShow*f),0!=this.slideCount%this.options.slidesToScroll&&a+this.options.slidesToScroll>
this.slideCount&&this.slideCount>this.options.slidesToShow&&(a>this.slideCount?(this.slideOffset=-1*(this.options.slidesToShow-(a-this.slideCount))*this.slideWidth,c=-1*(this.options.slidesToShow-(a-this.slideCount))*b):(this.slideOffset=-1*this.slideCount%this.options.slidesToScroll*this.slideWidth,c=-1*this.slideCount%this.options.slidesToScroll*b))):a+this.options.slidesToShow>this.slideCount&&(this.slideOffset=(a+this.options.slidesToShow-this.slideCount)*this.slideWidth,c=(a+this.options.slidesToShow-
this.slideCount)*b),this.slideCount<=this.options.slidesToShow&&(this.slideOffset=0,c=0),!0===this.options.centerMode&&this.slideCount<=this.options.slidesToShow?this.slideOffset=this.slideWidth*Math.floor(this.options.slidesToShow)/2-this.slideWidth*this.slideCount/2:!0===this.options.centerMode&&!0===this.options.infinite?this.slideOffset+=this.slideWidth*Math.floor(this.options.slidesToShow/2)-this.slideWidth:!0===this.options.centerMode&&(this.slideOffset=0,this.slideOffset+=this.slideWidth*Math.floor(this.options.slidesToShow/
2)),d=!1===this.options.vertical?-1*a*this.slideWidth+this.slideOffset:-1*a*b+c,!0===this.options.variableWidth&&(e=this.slideCount<=this.options.slidesToShow||!1===this.options.infinite?this.$slideTrack.children(".slick-slide").eq(a):this.$slideTrack.children(".slick-slide").eq(a+this.options.slidesToShow),d=!0===this.options.rtl?e[0]?-1*(this.$slideTrack.width()-e[0].offsetLeft-e.width()):0:e[0]?-1*e[0].offsetLeft:0,!0===this.options.centerMode&&(e=this.slideCount<=this.options.slidesToShow||!1===
this.options.infinite?this.$slideTrack.children(".slick-slide").eq(a):this.$slideTrack.children(".slick-slide").eq(a+this.options.slidesToShow+1),d=!0===this.options.rtl?e[0]?-1*(this.$slideTrack.width()-e[0].offsetLeft-e.width()):0:e[0]?-1*e[0].offsetLeft:0,d+=(this.$list.width()-e.outerWidth())/2)),d};c.prototype.getOption=c.prototype.slickGetOption=function(a){return this.options[a]};c.prototype.getNavigableIndexes=function(){var a,d=0,b=0,e=[];for(!1===this.options.infinite?a=this.slideCount:
(d=-1*this.options.slidesToScroll,b=-1*this.options.slidesToScroll,a=2*this.slideCount);d<a;)e.push(d),d=b+this.options.slidesToScroll,b+=this.options.slidesToScroll<=this.options.slidesToShow?this.options.slidesToScroll:this.options.slidesToShow;return e};c.prototype.getSlick=function(){return this};c.prototype.getSlideCount=function(){var a,d,g=this;return d=!0===g.options.centerMode?g.slideWidth*Math.floor(g.options.slidesToShow/2):0,!0===g.options.swipeToSlide?(g.$slideTrack.find(".slick-slide").each(function(e,
f){if(f.offsetLeft-d+b(f).outerWidth()/2>-1*g.swipeLeft)return a=f,!1}),Math.abs(b(a).attr("data-slick-index")-g.currentSlide)||1):g.options.slidesToScroll};c.prototype.goTo=c.prototype.slickGoTo=function(a,d){this.changeSlide({data:{message:"index",index:parseInt(a)}},d)};c.prototype.init=function(a){b(this.$slider).hasClass("slick-initialized")||(b(this.$slider).addClass("slick-initialized"),this.buildRows(),this.buildOut(),this.setProps(),this.startLoad(),this.loadSlider(),this.initializeEvents(),
this.updateArrows(),this.updateDots(),this.checkResponsive(!0),this.focusHandler());a&&this.$slider.trigger("init",[this]);!0===this.options.accessibility&&this.initADA();this.options.autoplay&&(this.paused=!1,this.autoPlay())};c.prototype.initADA=function(){var a=this,d=Math.ceil(a.slideCount/a.options.slidesToShow),g=a.getNavigableIndexes().filter(function(d){return 0<=d&&d<a.slideCount});a.$slides.add(a.$slideTrack.find(".slick-cloned")).attr({"aria-hidden":"true",tabindex:"-1"}).find("a, input, button, select").attr({tabindex:"-1"});
null!==a.$dots&&(a.$slides.not(a.$slideTrack.find(".slick-cloned")).each(function(d){var e=g.indexOf(d);b(this).attr({role:"tabpanel",id:"slick-slide"+a.instanceUid+d,tabindex:-1});-1!==e&&b(this).attr({"aria-describedby":"slick-slide-control"+a.instanceUid+e})}),a.$dots.attr("role","tablist").find("li").each(function(e){var f=g[e];b(this).attr({role:"presentation"});b(this).find("button").first().attr({role:"tab",id:"slick-slide-control"+a.instanceUid+e,"aria-controls":"slick-slide"+a.instanceUid+
f,"aria-label":e+1+" of "+d,"aria-selected":null,tabindex:"-1"})}).eq(a.currentSlide).find("button").attr({"aria-selected":"true",tabindex:"0"}).end());for(var e=a.currentSlide,f=e+a.options.slidesToShow;e<f;e++)a.$slides.eq(e).attr("tabindex",0);a.activateADA()};c.prototype.initArrowEvents=function(){!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&(this.$prevArrow.off("click.slick").on("click.slick",{message:"previous"},this.changeSlide),this.$nextArrow.off("click.slick").on("click.slick",
{message:"next"},this.changeSlide),!0===this.options.accessibility&&(this.$prevArrow.on("keydown.slick",this.keyHandler),this.$nextArrow.on("keydown.slick",this.keyHandler)))};c.prototype.initDotEvents=function(){!0===this.options.dots&&(b("li",this.$dots).on("click.slick",{message:"index"},this.changeSlide),!0===this.options.accessibility&&this.$dots.on("keydown.slick",this.keyHandler));!0===this.options.dots&&!0===this.options.pauseOnDotsHover&&b("li",this.$dots).on("mouseenter.slick",b.proxy(this.interrupt,
this,!0)).on("mouseleave.slick",b.proxy(this.interrupt,this,!1))};c.prototype.initSlideEvents=function(){this.options.pauseOnHover&&(this.$list.on("mouseenter.slick",b.proxy(this.interrupt,this,!0)),this.$list.on("mouseleave.slick",b.proxy(this.interrupt,this,!1)))};c.prototype.initializeEvents=function(){this.initArrowEvents();this.initDotEvents();this.initSlideEvents();this.$list.on("touchstart.slick mousedown.slick",{action:"start"},this.swipeHandler);this.$list.on("touchmove.slick mousemove.slick",
{action:"move"},this.swipeHandler);this.$list.on("touchend.slick mouseup.slick",{action:"end"},this.swipeHandler);this.$list.on("touchcancel.slick mouseleave.slick",{action:"end"},this.swipeHandler);this.$list.on("click.slick",this.clickHandler);b(document).on(this.visibilityChange,b.proxy(this.visibility,this));!0===this.options.accessibility&&this.$list.on("keydown.slick",this.keyHandler);!0===this.options.focusOnSelect&&b(this.$slideTrack).children().on("click.slick",this.selectHandler);b(window).on("orientationchange.slick.slick-"+
this.instanceUid,b.proxy(this.orientationChange,this));b(window).on("resize.slick.slick-"+this.instanceUid,b.proxy(this.resize,this));b("[draggable!\x3dtrue]",this.$slideTrack).on("dragstart",this.preventDefault);b(window).on("load.slick.slick-"+this.instanceUid,this.setPosition);b(this.setPosition)};c.prototype.initUI=function(){!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&(this.$prevArrow.show(),this.$nextArrow.show());!0===this.options.dots&&this.slideCount>this.options.slidesToShow&&
this.$dots.show()};c.prototype.keyHandler=function(a){a.target.tagName.match("TEXTAREA|INPUT|SELECT")||(37===a.keyCode&&!0===this.options.accessibility?this.changeSlide({data:{message:!0===this.options.rtl?"next":"previous"}}):39===a.keyCode&&!0===this.options.accessibility&&this.changeSlide({data:{message:!0===this.options.rtl?"previous":"next"}}))};c.prototype.lazyLoad=function(){function a(a){b("img[data-lazy]",a).each(function(){var a=b(this),d=b(this).attr("data-lazy"),e=b(this).attr("data-srcset"),
n=b(this).attr("data-sizes")||f.$slider.attr("data-sizes"),g=document.createElement("img");g.onload=function(){a.animate({opacity:0},100,function(){e&&(a.attr("srcset",e),n&&a.attr("sizes",n));a.attr("src",d).animate({opacity:1},200,function(){a.removeAttr("data-lazy data-srcset data-sizes").removeClass("slick-loading")});f.$slider.trigger("lazyLoaded",[f,a,d])})};g.onerror=function(){a.removeAttr("data-lazy").removeClass("slick-loading").addClass("slick-lazyload-error");f.$slider.trigger("lazyLoadError",
[f,a,d])};g.src=d})}var d,g,e,f=this;if(!0===f.options.centerMode?!0===f.options.infinite?e=(g=f.currentSlide+(f.options.slidesToShow/2+1))+f.options.slidesToShow+2:(g=Math.max(0,f.currentSlide-(f.options.slidesToShow/2+1)),e=f.options.slidesToShow/2+3+f.currentSlide):(g=f.options.infinite?f.options.slidesToShow+f.currentSlide:f.currentSlide,e=Math.ceil(g+f.options.slidesToShow),!0===f.options.fade&&(0<g&&g--,e<=f.slideCount&&e++)),d=f.$slider.find(".slick-slide").slice(g,e),"anticipated"===f.options.lazyLoad){g-=
1;for(var c=f.$slider.find(".slick-slide"),k=0;k<f.options.slidesToScroll;k++)0>g&&(g=f.slideCount-1),d=(d=d.add(c.eq(g))).add(c.eq(e)),g--,e++}a(d);f.slideCount<=f.options.slidesToShow?a(f.$slider.find(".slick-slide")):f.currentSlide>=f.slideCount-f.options.slidesToShow?a(f.$slider.find(".slick-cloned").slice(0,f.options.slidesToShow)):0===f.currentSlide&&a(f.$slider.find(".slick-cloned").slice(-1*f.options.slidesToShow))};c.prototype.loadSlider=function(){this.setPosition();this.$slideTrack.css({opacity:1});
this.$slider.removeClass("slick-loading");this.initUI();"progressive"===this.options.lazyLoad&&this.progressiveLazyLoad()};c.prototype.next=c.prototype.slickNext=function(){this.changeSlide({data:{message:"next"}})};c.prototype.orientationChange=function(){this.checkResponsive();this.setPosition()};c.prototype.pause=c.prototype.slickPause=function(){this.autoPlayClear();this.paused=!0};c.prototype.play=c.prototype.slickPlay=function(){this.autoPlay();this.options.autoplay=!0;this.interrupted=this.focussed=
this.paused=!1};c.prototype.postSlide=function(a){this.unslicked||(this.$slider.trigger("afterChange",[this,a]),this.animating=!1,this.slideCount>this.options.slidesToShow&&this.setPosition(),this.swipeLeft=null,this.options.autoplay&&this.autoPlay(),!0===this.options.accessibility&&(this.initADA(),this.options.focusOnChange&&b(this.$slides.get(this.currentSlide)).attr("tabindex",0).focus()))};c.prototype.prev=c.prototype.slickPrev=function(){this.changeSlide({data:{message:"previous"}})};c.prototype.preventDefault=
function(a){a.preventDefault()};c.prototype.progressiveLazyLoad=function(a){a=a||1;var d,g,e,f,c,k=this,h=b("img[data-lazy]",k.$slider);h.length?(d=h.first(),g=d.attr("data-lazy"),e=d.attr("data-srcset"),f=d.attr("data-sizes")||k.$slider.attr("data-sizes"),(c=document.createElement("img")).onload=function(){e&&(d.attr("srcset",e),f&&d.attr("sizes",f));d.attr("src",g).removeAttr("data-lazy data-srcset data-sizes").removeClass("slick-loading");!0===k.options.adaptiveHeight&&k.setPosition();k.$slider.trigger("lazyLoaded",
[k,d,g]);k.progressiveLazyLoad()},c.onerror=function(){3>a?setTimeout(function(){k.progressiveLazyLoad(a+1)},500):(d.removeAttr("data-lazy").removeClass("slick-loading").addClass("slick-lazyload-error"),k.$slider.trigger("lazyLoadError",[k,d,g]),k.progressiveLazyLoad())},c.src=g):k.$slider.trigger("allImagesLoaded",[k])};c.prototype.refresh=function(a){var d;d=this.slideCount-this.options.slidesToShow;!this.options.infinite&&this.currentSlide>d&&(this.currentSlide=d);this.slideCount<=this.options.slidesToShow&&
(this.currentSlide=0);d=this.currentSlide;this.destroy(!0);b.extend(this,this.initials,{currentSlide:d});this.init();a||this.changeSlide({data:{message:"index",index:d}},!1)};c.prototype.registerBreakpoints=function(){var a,d,g,e=this,f=e.options.responsive||null;if("array"===b.type(f)&&f.length){e.respondTo=e.options.respondTo||"window";for(a in f)if(g=e.breakpoints.length-1,f.hasOwnProperty(a)){for(d=f[a].breakpoint;0<=g;)e.breakpoints[g]&&e.breakpoints[g]===d&&e.breakpoints.splice(g,1),g--;e.breakpoints.push(d);
e.breakpointSettings[d]=f[a].settings}e.breakpoints.sort(function(a,d){return e.options.mobileFirst?a-d:d-a})}};c.prototype.reinit=function(){this.$slides=this.$slideTrack.children(this.options.slide).addClass("slick-slide");this.slideCount=this.$slides.length;this.currentSlide>=this.slideCount&&0!==this.currentSlide&&(this.currentSlide-=this.options.slidesToScroll);this.slideCount<=this.options.slidesToShow&&(this.currentSlide=0);this.registerBreakpoints();this.setProps();this.setupInfinite();this.buildArrows();
this.updateArrows();this.initArrowEvents();this.buildDots();this.updateDots();this.initDotEvents();this.cleanUpSlideEvents();this.initSlideEvents();this.checkResponsive(!1,!0);!0===this.options.focusOnSelect&&b(this.$slideTrack).children().on("click.slick",this.selectHandler);this.setSlideClasses("number"==typeof this.currentSlide?this.currentSlide:0);this.setPosition();this.focusHandler();this.paused=!this.options.autoplay;this.autoPlay();this.$slider.trigger("reInit",[this])};c.prototype.resize=
function(){var a=this;b(window).width()!==a.windowWidth&&(clearTimeout(a.windowDelay),a.windowDelay=window.setTimeout(function(){a.windowWidth=b(window).width();a.checkResponsive();a.unslicked||a.setPosition()},50))};c.prototype.removeSlide=c.prototype.slickRemove=function(a,d,b){if(a="boolean"==typeof a?!0===a?0:this.slideCount-1:!0===d?--a:a,1>this.slideCount||0>a||a>this.slideCount-1)return!1;this.unload();!0===b?this.$slideTrack.children().remove():this.$slideTrack.children(this.options.slide).eq(a).remove();
this.$slides=this.$slideTrack.children(this.options.slide);this.$slideTrack.children(this.options.slide).detach();this.$slideTrack.append(this.$slides);this.$slidesCache=this.$slides;this.reinit()};c.prototype.setCSS=function(a){var d,b,e={};!0===this.options.rtl&&(a=-a);d="left"==this.positionProp?Math.ceil(a)+"px":"0px";b="top"==this.positionProp?Math.ceil(a)+"px":"0px";e[this.positionProp]=a;!1===this.transformsEnabled?this.$slideTrack.css(e):(e={},!1===this.cssTransitions?(e[this.animType]="translate("+
d+", "+b+")",this.$slideTrack.css(e)):(e[this.animType]="translate3d("+d+", "+b+", 0px)",this.$slideTrack.css(e)))};c.prototype.setDimensions=function(){!1===this.options.vertical?!0===this.options.centerMode&&this.$list.css({padding:"0px "+this.options.centerPadding}):(this.$list.height(this.$slides.first().outerHeight(!0)*this.options.slidesToShow),!0===this.options.centerMode&&this.$list.css({padding:this.options.centerPadding+" 0px"}));this.listWidth=this.$list.width();this.listHeight=this.$list.height();
!1===this.options.vertical&&!1===this.options.variableWidth?(this.slideWidth=Math.ceil(this.listWidth/this.options.slidesToShow),this.$slideTrack.width(Math.ceil(this.slideWidth*this.$slideTrack.children(".slick-slide").length))):!0===this.options.variableWidth?this.$slideTrack.width(5E3*this.slideCount):(this.slideWidth=Math.ceil(this.listWidth),this.$slideTrack.height(Math.ceil(this.$slides.first().outerHeight(!0)*this.$slideTrack.children(".slick-slide").length)));var a=this.$slides.first().outerWidth(!0)-
this.$slides.first().width();!1===this.options.variableWidth&&this.$slideTrack.children(".slick-slide").width(this.slideWidth-a)};c.prototype.setFade=function(){var a,d=this;d.$slides.each(function(c,e){a=-1*d.slideWidth*c;!0===d.options.rtl?b(e).css({position:"relative",right:a,top:0,zIndex:d.options.zIndex-2,opacity:0}):b(e).css({position:"relative",left:a,top:0,zIndex:d.options.zIndex-2,opacity:0})});d.$slides.eq(d.currentSlide).css({zIndex:d.options.zIndex-1,opacity:1})};c.prototype.setHeight=
function(){if(1===this.options.slidesToShow&&!0===this.options.adaptiveHeight&&!1===this.options.vertical){var a=this.$slides.eq(this.currentSlide).outerHeight(!0);this.$list.css("height",a)}};c.prototype.setOption=c.prototype.slickSetOption=function(a,d,c){var e,f,h,k,l=this,i=!1;if("object"===b.type(a)?(f=a,i=d,k="multiple"):"string"===b.type(a)&&(f=a,h=d,i=c,"responsive"===a&&"array"===b.type(d)?k="responsive":void 0!==d&&(k="single")),"single"===k)l.options[f]=h;else if("multiple"===k)b.each(f,
function(a,d){l.options[a]=d});else if("responsive"===k)for(e in h)if("array"!==b.type(l.options.responsive))l.options.responsive=[h[e]];else{for(a=l.options.responsive.length-1;0<=a;)l.options.responsive[a].breakpoint===h[e].breakpoint&&l.options.responsive.splice(a,1),a--;l.options.responsive.push(h[e])}i&&(l.unload(),l.reinit())};c.prototype.setPosition=function(){this.setDimensions();this.setHeight();!1===this.options.fade?this.setCSS(this.getLeft(this.currentSlide)):this.setFade();this.$slider.trigger("setPosition",
[this])};c.prototype.setProps=function(){var a=document.body.style;this.positionProp=!0===this.options.vertical?"top":"left";"top"===this.positionProp?this.$slider.addClass("slick-vertical"):this.$slider.removeClass("slick-vertical");void 0===a.WebkitTransition&&void 0===a.MozTransition&&void 0===a.msTransition||!0===this.options.useCSS&&(this.cssTransitions=!0);this.options.fade&&("number"==typeof this.options.zIndex?3>this.options.zIndex&&(this.options.zIndex=3):this.options.zIndex=this.defaults.zIndex);
void 0!==a.OTransform&&(this.animType="OTransform",this.transformType="-o-transform",this.transitionType="OTransition",void 0===a.perspectiveProperty&&void 0===a.webkitPerspective&&(this.animType=!1));void 0!==a.MozTransform&&(this.animType="MozTransform",this.transformType="-moz-transform",this.transitionType="MozTransition",void 0===a.perspectiveProperty&&void 0===a.MozPerspective&&(this.animType=!1));void 0!==a.webkitTransform&&(this.animType="webkitTransform",this.transformType="-webkit-transform",
this.transitionType="webkitTransition",void 0===a.perspectiveProperty&&void 0===a.webkitPerspective&&(this.animType=!1));void 0!==a.msTransform&&(this.animType="msTransform",this.transformType="-ms-transform",this.transitionType="msTransition",void 0===a.msTransform&&(this.animType=!1));void 0!==a.transform&&!1!==this.animType&&(this.animType="transform",this.transformType="transform",this.transitionType="transition");this.transformsEnabled=this.options.useTransform&&null!==this.animType&&!1!==this.animType};
c.prototype.setSlideClasses=function(a){var d,b,e;if(b=this.$slider.find(".slick-slide").removeClass("slick-active slick-center slick-current").attr("aria-hidden","true"),this.$slides.eq(a).addClass("slick-current"),!0===this.options.centerMode){var f=0==this.options.slidesToShow%2?1:0;d=Math.floor(this.options.slidesToShow/2);!0===this.options.infinite&&(a>=d&&a<=this.slideCount-1-d?this.$slides.slice(a-d+f,a+d+1).addClass("slick-active").attr("aria-hidden","false"):(e=this.options.slidesToShow+
a,b.slice(e-d+1+f,e+d+2).addClass("slick-active").attr("aria-hidden","false")),0===a?b.eq(b.length-1-this.options.slidesToShow).addClass("slick-center"):a===this.slideCount-1&&b.eq(this.options.slidesToShow).addClass("slick-center"));this.$slides.eq(a).addClass("slick-center")}else 0<=a&&a<=this.slideCount-this.options.slidesToShow?this.$slides.slice(a,a+this.options.slidesToShow).addClass("slick-active").attr("aria-hidden","false"):b.length<=this.options.slidesToShow?b.addClass("slick-active").attr("aria-hidden",
"false"):(d=this.slideCount%this.options.slidesToShow,e=!0===this.options.infinite?this.options.slidesToShow+a:a,this.options.slidesToShow==this.options.slidesToScroll&&this.slideCount-a<this.options.slidesToShow?b.slice(e-(this.options.slidesToShow-d),e+d).addClass("slick-active").attr("aria-hidden","false"):b.slice(e,e+this.options.slidesToShow).addClass("slick-active").attr("aria-hidden","false"));"ondemand"!==this.options.lazyLoad&&"anticipated"!==this.options.lazyLoad||this.lazyLoad()};c.prototype.setupInfinite=
function(){var a,d,c;if(!0===this.options.fade&&(this.options.centerMode=!1),!0===this.options.infinite&&!1===this.options.fade&&(d=null,this.slideCount>this.options.slidesToShow)){c=!0===this.options.centerMode?this.options.slidesToShow+1:this.options.slidesToShow;for(a=this.slideCount;a>this.slideCount-c;a-=1)d=a-1,b(this.$slides[d]).clone(!0).attr("id","").attr("data-slick-index",d-this.slideCount).prependTo(this.$slideTrack).addClass("slick-cloned");for(a=0;a<c+this.slideCount;a+=1)d=a,b(this.$slides[d]).clone(!0).attr("id",
"").attr("data-slick-index",d+this.slideCount).appendTo(this.$slideTrack).addClass("slick-cloned");this.$slideTrack.find(".slick-cloned").find("[id]").each(function(){b(this).attr("id","")})}};c.prototype.interrupt=function(a){a||this.autoPlay();this.interrupted=a};c.prototype.selectHandler=function(a){a=b(a.target).is(".slick-slide")?b(a.target):b(a.target).parents(".slick-slide");(a=parseInt(a.attr("data-slick-index")))||(a=0);this.slideCount<=this.options.slidesToShow?this.slideHandler(a,!1,!0):
this.slideHandler(a)};c.prototype.slideHandler=function(a,d,b){var e,f,c,h,l=null,i=this;if(d=d||!1,!(!0===i.animating&&!0===i.options.waitForAnimate||!0===i.options.fade&&i.currentSlide===a))if(!1===d&&i.asNavFor(a),e=a,l=i.getLeft(e),c=i.getLeft(i.currentSlide),i.currentLeft=null===i.swipeLeft?c:i.swipeLeft,!1===i.options.infinite&&!1===i.options.centerMode&&(0>a||a>i.getDotCount()*i.options.slidesToScroll))!1===i.options.fade&&(e=i.currentSlide,!0!==b?i.animateSlide(c,function(){i.postSlide(e)}):
i.postSlide(e));else if(!1===i.options.infinite&&!0===i.options.centerMode&&(0>a||a>i.slideCount-i.options.slidesToScroll))!1===i.options.fade&&(e=i.currentSlide,!0!==b?i.animateSlide(c,function(){i.postSlide(e)}):i.postSlide(e));else{if(i.options.autoplay&&clearInterval(i.autoPlayTimer),f=0>e?0!=i.slideCount%i.options.slidesToScroll?i.slideCount-i.slideCount%i.options.slidesToScroll:i.slideCount+e:e>=i.slideCount?0!=i.slideCount%i.options.slidesToScroll?0:e-i.slideCount:e,i.animating=!0,i.$slider.trigger("beforeChange",
[i,i.currentSlide,f]),a=i.currentSlide,i.currentSlide=f,i.setSlideClasses(i.currentSlide),i.options.asNavFor&&(h=(h=i.getNavTarget()).slick("getSlick")).slideCount<=h.options.slidesToShow&&h.setSlideClasses(i.currentSlide),i.updateDots(),i.updateArrows(),!0===i.options.fade)return!0!==b?(i.fadeSlideOut(a),i.fadeSlide(f,function(){i.postSlide(f)})):i.postSlide(f),void i.animateHeight();!0!==b?i.animateSlide(l,function(){i.postSlide(f)}):i.postSlide(f)}};c.prototype.startLoad=function(){!0===this.options.arrows&&
this.slideCount>this.options.slidesToShow&&(this.$prevArrow.hide(),this.$nextArrow.hide());!0===this.options.dots&&this.slideCount>this.options.slidesToShow&&this.$dots.hide();this.$slider.addClass("slick-loading")};c.prototype.swipeDirection=function(){var a,d,b,e;return a=this.touchObject.startX-this.touchObject.curX,d=this.touchObject.startY-this.touchObject.curY,b=Math.atan2(d,a),0>(e=Math.round(180*b/Math.PI))&&(e=360-Math.abs(e)),45>=e&&0<=e?!1===this.options.rtl?"left":"right":360>=e&&315<=
e?!1===this.options.rtl?"left":"right":135<=e&&225>=e?!1===this.options.rtl?"right":"left":!0===this.options.verticalSwiping?35<=e&&135>=e?"down":"up":"vertical"};c.prototype.swipeEnd=function(){var a,d;if(this.dragging=!1,this.swiping=!1,this.scrolling)return this.scrolling=!1,!1;if(this.interrupted=!1,this.shouldClick=!(10<this.touchObject.swipeLength),void 0===this.touchObject.curX)return!1;if(!0===this.touchObject.edgeHit&&this.$slider.trigger("edge",[this,this.swipeDirection()]),this.touchObject.swipeLength>=
this.touchObject.minSwipe){switch(d=this.swipeDirection()){case "left":case "down":a=this.options.swipeToSlide?this.checkNavigable(this.currentSlide+this.getSlideCount()):this.currentSlide+this.getSlideCount();this.currentDirection=0;break;case "right":case "up":a=this.options.swipeToSlide?this.checkNavigable(this.currentSlide-this.getSlideCount()):this.currentSlide-this.getSlideCount(),this.currentDirection=1}"vertical"!=d&&(this.slideHandler(a),this.touchObject={},this.$slider.trigger("swipe",[this,
d]))}else this.touchObject.startX!==this.touchObject.curX&&(this.slideHandler(this.currentSlide),this.touchObject={})};c.prototype.swipeHandler=function(a){if(!(!1===this.options.swipe||"ontouchend"in document&&!1===this.options.swipe||!1===this.options.draggable&&-1!==a.type.indexOf("mouse")))switch(this.touchObject.fingerCount=a.originalEvent&&void 0!==a.originalEvent.touches?a.originalEvent.touches.length:1,this.touchObject.minSwipe=this.listWidth/this.options.touchThreshold,!0===this.options.verticalSwiping&&
(this.touchObject.minSwipe=this.listHeight/this.options.touchThreshold),a.data.action){case "start":this.swipeStart(a);break;case "move":this.swipeMove(a);break;case "end":this.swipeEnd(a)}};c.prototype.swipeMove=function(a){var d,b,e,c,h,k;return h=void 0!==a.originalEvent?a.originalEvent.touches:null,!(!this.dragging||this.scrolling||h&&1!==h.length)&&(d=this.getLeft(this.currentSlide),this.touchObject.curX=void 0!==h?h[0].pageX:a.clientX,this.touchObject.curY=void 0!==h?h[0].pageY:a.clientY,this.touchObject.swipeLength=
Math.round(Math.sqrt(Math.pow(this.touchObject.curX-this.touchObject.startX,2))),k=Math.round(Math.sqrt(Math.pow(this.touchObject.curY-this.touchObject.startY,2))),!this.options.verticalSwiping&&!this.swiping&&4<k?(this.scrolling=!0,!1):(!0===this.options.verticalSwiping&&(this.touchObject.swipeLength=k),b=this.swipeDirection(),void 0!==a.originalEvent&&4<this.touchObject.swipeLength&&(this.swiping=!0,a.preventDefault()),c=(!1===this.options.rtl?1:-1)*(this.touchObject.curX>this.touchObject.startX?
1:-1),!0===this.options.verticalSwiping&&(c=this.touchObject.curY>this.touchObject.startY?1:-1),e=this.touchObject.swipeLength,this.touchObject.edgeHit=!1,!1===this.options.infinite&&(0===this.currentSlide&&"right"===b||this.currentSlide>=this.getDotCount()&&"left"===b)&&(e=this.touchObject.swipeLength*this.options.edgeFriction,this.touchObject.edgeHit=!0),!1===this.options.vertical?this.swipeLeft=d+e*c:this.swipeLeft=d+e*(this.$list.height()/this.listWidth)*c,!0===this.options.verticalSwiping&&(this.swipeLeft=
d+e*c),!0!==this.options.fade&&!1!==this.options.touchMove&&(!0===this.animating?(this.swipeLeft=null,!1):void this.setCSS(this.swipeLeft))))};c.prototype.swipeStart=function(a){var d;if(this.interrupted=!0,1!==this.touchObject.fingerCount||this.slideCount<=this.options.slidesToShow)return this.touchObject={},!1;void 0!==a.originalEvent&&void 0!==a.originalEvent.touches&&(d=a.originalEvent.touches[0]);this.touchObject.startX=this.touchObject.curX=void 0!==d?d.pageX:a.clientX;this.touchObject.startY=
this.touchObject.curY=void 0!==d?d.pageY:a.clientY;this.dragging=!0};c.prototype.unfilterSlides=c.prototype.slickUnfilter=function(){null!==this.$slidesCache&&(this.unload(),this.$slideTrack.children(this.options.slide).detach(),this.$slidesCache.appendTo(this.$slideTrack),this.reinit())};c.prototype.unload=function(){b(".slick-cloned",this.$slider).remove();this.$dots&&this.$dots.remove();this.$prevArrow&&this.htmlExpr.test(this.options.prevArrow)&&this.$prevArrow.remove();this.$nextArrow&&this.htmlExpr.test(this.options.nextArrow)&&
this.$nextArrow.remove();this.$slides.removeClass("slick-slide slick-active slick-visible slick-current").attr("aria-hidden","true").css("width","")};c.prototype.unslick=function(a){this.$slider.trigger("unslick",[this,a]);this.destroy()};c.prototype.updateArrows=function(){Math.floor(this.options.slidesToShow/2);!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&!this.options.infinite&&(this.$prevArrow.removeClass("slick-disabled").attr("aria-disabled","false"),this.$nextArrow.removeClass("slick-disabled").attr("aria-disabled",
"false"),0===this.currentSlide?(this.$prevArrow.addClass("slick-disabled").attr("aria-disabled","true"),this.$nextArrow.removeClass("slick-disabled").attr("aria-disabled","false")):this.currentSlide>=this.slideCount-this.options.slidesToShow&&!1===this.options.centerMode?(this.$nextArrow.addClass("slick-disabled").attr("aria-disabled","true"),this.$prevArrow.removeClass("slick-disabled").attr("aria-disabled","false")):this.currentSlide>=this.slideCount-1&&!0===this.options.centerMode&&(this.$nextArrow.addClass("slick-disabled").attr("aria-disabled",
"true"),this.$prevArrow.removeClass("slick-disabled").attr("aria-disabled","false")))};c.prototype.updateDots=function(){null!==this.$dots&&(this.$dots.find("li").removeClass("slick-active").end(),this.$dots.find("li").eq(Math.floor(this.currentSlide/this.options.slidesToScroll)).addClass("slick-active"))};c.prototype.visibility=function(){this.options.autoplay&&(document[this.hidden]?this.interrupted=!0:this.interrupted=!1)};b.fn.slick=function(){var a,d,b=arguments[0],e=Array.prototype.slice.call(arguments,
1),f=this.length;for(a=0;a<f;a++)if("object"==typeof b||void 0===b?this[a].slick=new c(this[a],b):d=this[a].slick[b].apply(this[a].slick,e),void 0!==d)return d;return this}});
!function(b){b.fn.niceSelect=function(c){function h(a){a.after(b("\x3cdiv\x3e\x3c/div\x3e").addClass("nice-select").addClass(a.attr("class")||"").addClass(a.attr("disabled")?"disabled":"").attr("tabindex",a.attr("disabled")?null:"0").html('\x3cspan class\x3d"current"\x3e\x3c/span\x3e\x3cul class\x3d"list"\x3e\x3c/ul\x3e'));var d=a.next(),c=a.find("option");a=a.find("option:selected");d.find(".current").html(a.data("display")||a.text());c.each(function(){var a=b(this),c=a.data("display");d.find("ul").append(b("\x3cli\x3e\x3c/li\x3e").attr("data-value",
a.val()).attr("data-display",c||null).addClass("option"+(a.is(":selected")?" selected":"")+(a.is(":disabled")?" disabled":"")).html(a.text()))})}if("string"==typeof c)return"update"==c?this.each(function(){var a=b(this),d=b(this).next(".nice-select"),c=d.hasClass("open");d.length&&(d.remove(),h(a),c&&a.next().trigger("click"))}):"destroy"==c?(this.each(function(){var a=b(this),d=b(this).next(".nice-select");d.length&&(d.remove(),a.css("display",""))}),0==b(".nice-select").length&&b(document).off(".nice_select")):
console.log('Method "'+c+'" does not exist.'),this;this.hide();this.each(function(){var a=b(this);a.next().hasClass("nice-select")||h(a)});b(document).off(".nice_select");b(document).on("click.nice_select",".nice-select",function(){var a=b(this);b(".nice-select").not(a).removeClass("open");a.toggleClass("open");a.hasClass("open")?(a.find(".option"),a.find(".focus").removeClass("focus"),a.find(".selected").addClass("focus")):a.focus()});b(document).on("click.nice_select",function(a){0===b(a.target).closest(".nice-select").length&&
b(".nice-select").removeClass("open").find(".option")});b(document).on("click.nice_select",".nice-select .option:not(.disabled)",function(){var a=b(this),d=a.closest(".nice-select");d.find(".selected").removeClass("selected");a.addClass("selected");var c=a.data("display")||a.text();d.find(".current").text(c);d.prev("select").val(a.data("value")).trigger("change")});b(document).on("keydown.nice_select",".nice-select",function(a){var d=b(this),c=b(d.find(".focus")||d.find(".list .option.selected"));
if(32==a.keyCode||13==a.keyCode)return d.hasClass("open")?c.trigger("click"):d.trigger("click"),!1;if(40==a.keyCode)return d.hasClass("open")?(a=c.nextAll(".option:not(.disabled)").first(),0<a.length&&(d.find(".focus").removeClass("focus"),a.addClass("focus"))):d.trigger("click"),!1;if(38==a.keyCode)return d.hasClass("open")?(a=c.prevAll(".option:not(.disabled)").first(),0<a.length&&(d.find(".focus").removeClass("focus"),a.addClass("focus"))):d.trigger("click"),!1;if(27==a.keyCode)d.hasClass("open")&&
d.trigger("click");else if(9==a.keyCode&&d.hasClass("open"))return!1});c=document.createElement("a").style;return c.cssText="pointer-events:auto","auto"!==c.pointerEvents&&b("html").addClass("no-csspointerevents"),this}}(jQuery);
!function(b,c){"function"==typeof define&&define.amd?define("jquery-bridget/jquery-bridget",["jquery"],function(h){return c(b,h)}):"object"==typeof module&&module.exports?module.exports=c(b,require("jquery")):b.jQueryBridget=c(b,b.jQuery)}(window,function(b,c){function h(d,e,k){if(k=k||c||b.jQuery)e.prototype.option||(e.prototype.option=function(a){k.isPlainObject(a)&&(this.options=k.extend(!0,this.options,a))}),k.fn[d]=function(b){if("string"==typeof b){var c=a.call(arguments,1),j=b,o=c,n,p="$()."+
d+'("'+j+'")';return this.each(function(a,b){var e=k.data(b,d);if(!e)return void g(d+" not initialized. Cannot call methods, i.e. "+p);var c=e[j];if(!c||"_"==j.charAt(0))return void g(p+" is not a valid method");e=c.apply(e,o);n=void 0===n?e:n}),void 0!==n?n:this}var h=b;this.each(function(a,b){var j=k.data(b,d);j?(j.option(h),j._init()):(j=new e(b,h),k.data(b,d,j))});return this},!k||k&&k.bridget||(k.bridget=h)}var a=Array.prototype.slice,d=b.console,g="undefined"==typeof d?function(){}:function(a){d.error(a)},
e=c||b.jQuery;!e||e&&e.bridget||(e.bridget=h);return h});
(function(b,c){"function"==typeof define&&define.amd?define("ev-emitter/ev-emitter",c):"object"==typeof module&&module.exports?module.exports=c():b.EvEmitter=c()})("undefined"!=typeof window?window:this,function(){function b(){}var c=b.prototype;return c.on=function(b,a){if(b&&a){var d=this._events=this._events||{},d=d[b]=d[b]||[];return-1==d.indexOf(a)&&d.push(a),this}},c.once=function(b,a){if(b&&a){this.on(b,a);var d=this._onceEvents=this._onceEvents||{};return(d[b]=d[b]||{})[a]=!0,this}},c.off=
function(b,a){var d=this._events&&this._events[b];if(d&&d.length){var c=d.indexOf(a);return-1!=c&&d.splice(c,1),this}},c.emitEvent=function(b,a){var d=this._events&&this._events[b];if(d&&d.length){var c=0,e=d[c];a=a||[];for(var f=this._onceEvents&&this._onceEvents[b];e;){var m=f&&f[e];m&&(this.off(b,e),delete f[e]);e.apply(this,a);c+=m?0:1;e=d[c]}return this}},b});
(function(b,c){"function"==typeof define&&define.amd?define("get-size/get-size",[],function(){return c()}):"object"==typeof module&&module.exports?module.exports=c():b.getSize=c()})(window,function(){function b(a){var d=parseFloat(a);return-1==a.indexOf("%")&&!isNaN(d)&&d}function c(){}function h(a){a=getComputedStyle(a);return a||g("Style returned "+a+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1"),a}function a(c){if(!m){m=!0;var g=document.createElement("div");
g.style.width="200px";g.style.padding="1px 2px 3px 4px";g.style.borderStyle="solid";g.style.borderWidth="1px 2px 3px 4px";g.style.boxSizing="border-box";var i=document.body||document.documentElement;i.appendChild(g);var j=h(g);a.isBoxSizeOuter=d=200==b(j.width);i.removeChild(g)}if("string"==typeof c&&(c=document.querySelector(c)),c&&"object"==typeof c&&c.nodeType){i=h(c);if("none"==i.display){g={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0};for(i=0;i<f;i++)g[e[i]]=0;return g}g=
{};g.width=c.offsetWidth;g.height=c.offsetHeight;c=g.isBorderBox="border-box"==i.boxSizing;for(j=0;j<f;j++){var o=e[j],n=parseFloat(i[o]);g[o]=isNaN(n)?0:n}var j=g.paddingLeft+g.paddingRight,o=g.paddingTop+g.paddingBottom,n=g.marginLeft+g.marginRight,p=g.marginTop+g.marginBottom,t=g.borderLeftWidth+g.borderRightWidth,q=g.borderTopWidth+g.borderBottomWidth;c=c&&d;var r=b(i.width);!1!==r&&(g.width=r+(c?0:j+t));i=b(i.height);return!1!==i&&(g.height=i+(c?0:o+q)),g.innerWidth=g.width-(j+t),g.innerHeight=
g.height-(o+q),g.outerWidth=g.width+n,g.outerHeight=g.height+p,g}}var d,g="undefined"==typeof console?c:function(a){console.error(a)},e="paddingLeft paddingRight paddingTop paddingBottom marginLeft marginRight marginTop marginBottom borderLeftWidth borderRightWidth borderTopWidth borderBottomWidth".split(" "),f=e.length,m=!1;return a});
(function(b,c){"function"==typeof define&&define.amd?define("desandro-matches-selector/matches-selector",c):"object"==typeof module&&module.exports?module.exports=c():b.matchesSelector=c()})(window,function(){var b=function(){var b=window.Element.prototype;if(b.matches)return"matches";if(b.matchesSelector)return"matchesSelector";for(var h=["webkit","moz","ms","o"],a=0;a<h.length;a++){var d=h[a]+"MatchesSelector";if(b[d])return d}}();return function(c,h){return c[b](h)}});
(function(b,c){"function"==typeof define&&define.amd?define("fizzy-ui-utils/utils",["desandro-matches-selector/matches-selector"],function(h){return c(b,h)}):"object"==typeof module&&module.exports?module.exports=c(b,require("desandro-matches-selector")):b.fizzyUIUtils=c(b,b.matchesSelector)})(window,function(b,c){var h={extend:function(a,b){for(var e in b)a[e]=b[e];return a},modulo:function(a,b){return(a%b+b)%b},makeArray:function(a){var b=[];if(Array.isArray(a))b=a;else if(a&&"object"==typeof a&&
"number"==typeof a.length)for(var e=0;e<a.length;e++)b.push(a[e]);else b.push(a);return b},removeFrom:function(a,b){var e=a.indexOf(b);-1!=e&&a.splice(e,1)},getParent:function(a,b){for(;a.parentNode&&a!=document.body;)if(a=a.parentNode,c(a,b))return a},getQueryElement:function(a){return"string"==typeof a?document.querySelector(a):a},handleEvent:function(a){var b="on"+a.type;this[b]&&this[b](a)},filterFindElements:function(a,b){a=h.makeArray(a);var e=[];return a.forEach(function(a){if(a instanceof
HTMLElement){if(!b)return void e.push(a);c(a,b)&&e.push(a);a=a.querySelectorAll(b);for(var d=0;d<a.length;d++)e.push(a[d])}}),e},debounceMethod:function(a,b,e){var c=a.prototype[b],h=b+"Timeout";a.prototype[b]=function(){var a=this[h];a&&clearTimeout(a);var b=arguments,d=this;this[h]=setTimeout(function(){c.apply(d,b);delete d[h]},e||100)}},docReady:function(a){var b=document.readyState;"complete"==b||"interactive"==b?setTimeout(a):document.addEventListener("DOMContentLoaded",a)},toDashed:function(a){return a.replace(/(.)([A-Z])/g,
function(a,b,d){return b+"-"+d}).toLowerCase()}},a=b.console;return h.htmlInit=function(d,c){h.docReady(function(){var e=h.toDashed(c),f="data-"+e,m=document.querySelectorAll("["+f+"]"),e=document.querySelectorAll(".js-"+e),m=h.makeArray(m).concat(h.makeArray(e)),k=f+"-options",l=b.jQuery;m.forEach(function(b){var j,e=b.getAttribute(f)||b.getAttribute(k);try{j=e&&JSON.parse(e)}catch(n){return void(a&&a.error("Error parsing "+f+" on "+b.className+": "+n))}j=new d(b,j);l&&l.data(b,c,j)})})},h});
(function(b,c){"function"==typeof define&&define.amd?define("outlayer/item",["ev-emitter/ev-emitter","get-size/get-size"],c):"object"==typeof module&&module.exports?module.exports=c(require("ev-emitter"),require("get-size")):(b.Outlayer={},b.Outlayer.Item=c(b.EvEmitter,b.getSize))})(window,function(b,c){function h(a,b){a&&(this.element=a,this.layout=b,this.position={x:0,y:0},this._create())}var a=document.documentElement.style,d="string"==typeof a.transition?"transition":"WebkitTransition",a="string"==
typeof a.transform?"transform":"WebkitTransform",g={WebkitTransition:"webkitTransitionEnd",transition:"transitionend"}[d],e={transform:a,transition:d,transitionDuration:d+"Duration",transitionProperty:d+"Property",transitionDelay:d+"Delay"},f=h.prototype=Object.create(b.prototype);f.constructor=h;f._create=function(){this._transn={ingProperties:{},clean:{},onEnd:{}};this.css({position:"absolute"})};f.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)};f.getSize=function(){this.size=c(this.element)};
f.css=function(a){var b=this.element.style,d;for(d in a)b[e[d]||d]=a[d]};f.getPosition=function(){var a=getComputedStyle(this.element),b=this.layout._getOption("originLeft"),d=this.layout._getOption("originTop"),c=a[b?"left":"right"],e=a[d?"top":"bottom"],a=this.layout.size,c=-1!=c.indexOf("%")?parseFloat(c)/100*a.width:parseInt(c,10),e=-1!=e.indexOf("%")?parseFloat(e)/100*a.height:parseInt(e,10),c=isNaN(c)?0:c,e=isNaN(e)?0:e,c=c-(b?a.paddingLeft:a.paddingRight),e=e-(d?a.paddingTop:a.paddingBottom);
this.position.x=c;this.position.y=e};f.layoutPosition=function(){var a=this.layout.size,b={},d=this.layout._getOption("originLeft"),c=this.layout._getOption("originTop"),e=d?"right":"left";b[d?"left":"right"]=this.getXValue(this.position.x+a[d?"paddingLeft":"paddingRight"]);b[e]="";d=c?"bottom":"top";b[c?"top":"bottom"]=this.getYValue(this.position.y+a[c?"paddingTop":"paddingBottom"]);b[d]="";this.css(b);this.emitEvent("layout",[this])};f.getXValue=function(a){var b=this.layout._getOption("horizontal");
return this.layout.options.percentPosition&&!b?100*(a/this.layout.size.width)+"%":a+"px"};f.getYValue=function(a){var b=this.layout._getOption("horizontal");return this.layout.options.percentPosition&&b?100*(a/this.layout.size.height)+"%":a+"px"};f._transitionTo=function(a,b){this.getPosition();var d=this.position.x,c=this.position.y,e=parseInt(a,10),f=parseInt(b,10),e=e===this.position.x&&f===this.position.y;if(this.setPosition(a,b),e&&!this.isTransitioning)return void this.layoutPosition();e={};
e.transform=this.getTranslate(a-d,b-c);this.transition({to:e,onTransitionEnd:{transform:this.layoutPosition},isCleaning:!0})};f.getTranslate=function(a,b){var d=this.layout._getOption("originLeft"),e=this.layout._getOption("originTop");return a=d?a:-a,b=e?b:-b,"translate3d("+a+"px, "+b+"px, 0)"};f.goTo=function(a,b){this.setPosition(a,b);this.layoutPosition()};f.moveTo=f._transitionTo;f.setPosition=function(a,b){this.position.x=parseInt(a,10);this.position.y=parseInt(b,10)};f._nonTransition=function(a){this.css(a.to);
a.isCleaning&&this._removeStyles(a.to);for(var b in a.onTransitionEnd)a.onTransitionEnd[b].call(this)};f.transition=function(a){if(!parseFloat(this.layout.options.transitionDuration))return void this._nonTransition(a);var b=this._transn,d;for(d in a.onTransitionEnd)b.onEnd[d]=a.onTransitionEnd[d];for(d in a.to)b.ingProperties[d]=!0,a.isCleaning&&(b.clean[d]=!0);a.from&&this.css(a.from);this.enableTransition(a.to);this.css(a.to);this.isTransitioning=!0};var m="opacity,"+a.replace(/([A-Z])/g,function(a){return"-"+
a.toLowerCase()});f.enableTransition=function(){if(!this.isTransitioning){var a=this.layout.options.transitionDuration;this.css({transitionProperty:m,transitionDuration:"number"==typeof a?a+"ms":a,transitionDelay:this.staggerDelay||0});this.element.addEventListener(g,this,!1)}};f.onwebkitTransitionEnd=function(a){this.ontransitionend(a)};f.onotransitionend=function(a){this.ontransitionend(a)};var k={"-webkit-transform":"transform"};f.ontransitionend=function(a){if(a.target===this.element){var b=this._transn,
d=k[a.propertyName]||a.propertyName;delete b.ingProperties[d];var e;a:{for(e in b.ingProperties){e=!1;break a}e=!0}if(e&&this.disableTransition(),d in b.clean&&(this.element.style[a.propertyName]="",delete b.clean[d]),d in b.onEnd)b.onEnd[d].call(this),delete b.onEnd[d];this.emitEvent("transitionEnd",[this])}};f.disableTransition=function(){this.removeTransitionStyles();this.element.removeEventListener(g,this,!1);this.isTransitioning=!1};f._removeStyles=function(a){var b={},d;for(d in a)b[d]="";this.css(b)};
var l={transitionProperty:"",transitionDuration:"",transitionDelay:""};return f.removeTransitionStyles=function(){this.css(l)},f.stagger=function(a){a=isNaN(a)?0:a;this.staggerDelay=a+"ms"},f.removeElem=function(){this.element.parentNode.removeChild(this.element);this.css({display:""});this.emitEvent("remove",[this])},f.remove=function(){return d&&parseFloat(this.layout.options.transitionDuration)?(this.once("transitionEnd",function(){this.removeElem()}),void this.hide()):void this.removeElem()},
f.reveal=function(){delete this.isHidden;this.css({display:""});var a=this.layout.options,b={},d=this.getHideRevealTransitionEndProperty("visibleStyle");b[d]=this.onRevealTransitionEnd;this.transition({from:a.hiddenStyle,to:a.visibleStyle,isCleaning:!0,onTransitionEnd:b})},f.onRevealTransitionEnd=function(){this.isHidden||this.emitEvent("reveal")},f.getHideRevealTransitionEndProperty=function(a){a=this.layout.options[a];if(a.opacity)return"opacity";for(var b in a)return b},f.hide=function(){this.isHidden=
!0;this.css({display:""});var a=this.layout.options,b={},d=this.getHideRevealTransitionEndProperty("hiddenStyle");b[d]=this.onHideTransitionEnd;this.transition({from:a.visibleStyle,to:a.hiddenStyle,isCleaning:!0,onTransitionEnd:b})},f.onHideTransitionEnd=function(){this.isHidden&&(this.css({display:"none"}),this.emitEvent("hide"))},f.destroy=function(){this.css({position:"",left:"",right:"",top:"",bottom:"",transition:"",transform:""})},h});
(function(b,c){"function"==typeof define&&define.amd?define("outlayer/outlayer",["ev-emitter/ev-emitter","get-size/get-size","fizzy-ui-utils/utils","./item"],function(h,a,d,g){return c(b,h,a,d,g)}):"object"==typeof module&&module.exports?module.exports=c(b,require("ev-emitter"),require("get-size"),require("fizzy-ui-utils"),require("./item")):b.Outlayer=c(b,b.EvEmitter,b.getSize,b.fizzyUIUtils,b.Outlayer.Item)})(window,function(b,c,h,a,d){function g(b,d){var e=a.getQueryElement(b);if(!e)return void(f&&
f.error("Bad element for "+this.constructor.namespace+": "+(e||b)));this.element=e;m&&(this.$element=m(this.element));this.options=a.extend({},this.constructor.defaults);this.option(d);e=++l;this.element.outlayerGUID=e;i[e]=this;this._create();this._getOption("initLayout")&&this.layout()}function e(a){function b(){a.apply(this,arguments)}return b.prototype=Object.create(a.prototype),b.prototype.constructor=b,b}var f=b.console,m=b.jQuery,k=function(){},l=0,i={};g.namespace="outlayer";g.Item=d;g.defaults=
{containerStyle:{position:"relative"},initLayout:!0,originLeft:!0,originTop:!0,resize:!0,resizeContainer:!0,transitionDuration:"0.4s",hiddenStyle:{opacity:0,transform:"scale(0.001)"},visibleStyle:{opacity:1,transform:"scale(1)"}};var j=g.prototype;a.extend(j,c.prototype);j.option=function(b){a.extend(this.options,b)};j._getOption=function(a){var b=this.constructor.compatOptions[a];return b&&void 0!==this.options[b]?this.options[b]:this.options[a]};g.compatOptions={initLayout:"isInitLayout",horizontal:"isHorizontal",
layoutInstant:"isLayoutInstant",originLeft:"isOriginLeft",originTop:"isOriginTop",resize:"isResizeBound",resizeContainer:"isResizingContainer"};j._create=function(){this.reloadItems();this.stamps=[];this.stamp(this.options.stamp);a.extend(this.element.style,this.options.containerStyle);this._getOption("resize")&&this.bindResize()};j.reloadItems=function(){this.items=this._itemize(this.element.children)};j._itemize=function(a){a=this._filterFindItemElements(a);for(var b=this.constructor.Item,d=[],
e=0;e<a.length;e++){var c=new b(a[e],this);d.push(c)}return d};j._filterFindItemElements=function(b){return a.filterFindElements(b,this.options.itemSelector)};j.getItemElements=function(){return this.items.map(function(a){return a.element})};j.layout=function(){this._resetLayout();this._manageStamps();var a=this._getOption("layoutInstant");this.layoutItems(this.items,void 0!==a?a:!this._isLayoutInited);this._isLayoutInited=!0};j._init=j.layout;j._resetLayout=function(){this.getSize()};j.getSize=function(){this.size=
h(this.element)};j._getMeasurement=function(a,b){var d,e=this.options[a];e?("string"==typeof e?d=this.element.querySelector(e):e instanceof HTMLElement&&(d=e),this[a]=d?h(d)[b]:e):this[a]=0};j.layoutItems=function(a,b){a=this._getItemsForLayout(a);this._layoutItems(a,b);this._postLayout()};j._getItemsForLayout=function(a){return a.filter(function(a){return!a.isIgnored})};j._layoutItems=function(a,b){if(this._emitCompleteOnItems("layout",a),a&&a.length){var d=[];a.forEach(function(a){var e=this._getItemLayoutPosition(a);
e.item=a;e.isInstant=b||a.isLayoutInstant;d.push(e)},this);this._processLayoutQueue(d)}};j._getItemLayoutPosition=function(){return{x:0,y:0}};j._processLayoutQueue=function(a){this.updateStagger();a.forEach(function(a,b){this._positionItem(a.item,a.x,a.y,a.isInstant,b)},this)};j.updateStagger=function(){var a=this.options.stagger;if(null===a||void 0===a)a=void(this.stagger=0);else{if("number"!=typeof a){var b=a.match(/(^\d*\.?\d*)(\w*)/),a=b&&b[1],b=b&&b[2];a.length?(a=parseFloat(a),a*=o[b]||1):a=
0}a=(this.stagger=a,this.stagger)}return a};j._positionItem=function(a,b,d,e,c){e?a.goTo(b,d):(a.stagger(c*this.stagger),a.moveTo(b,d))};j._postLayout=function(){this.resizeContainer()};j.resizeContainer=function(){if(this._getOption("resizeContainer")){var a=this._getContainerSize();a&&(this._setContainerMeasure(a.width,!0),this._setContainerMeasure(a.height,!1))}};j._getContainerSize=k;j._setContainerMeasure=function(a,b){if(void 0!==a){var d=this.size;d.isBorderBox&&(a+=b?d.paddingLeft+d.paddingRight+
d.borderLeftWidth+d.borderRightWidth:d.paddingBottom+d.paddingTop+d.borderTopWidth+d.borderBottomWidth);a=Math.max(a,0);this.element.style[b?"width":"height"]=a+"px"}};j._emitCompleteOnItems=function(a,b){function d(){c.dispatchEvent(a+"Complete",null,[b])}function e(){f++;f==j&&d()}var c=this,j=b.length;if(!b||!j)return void d();var f=0;b.forEach(function(b){b.once(a,e)})};j.dispatchEvent=function(a,b,d){var e=b?[b].concat(d):d;if(this.emitEvent(a,e),m)(this.$element=this.$element||m(this.element),
b)?(b=m.Event(b),b.type=a,this.$element.trigger(b,d)):this.$element.trigger(a,d)};j.ignore=function(a){(a=this.getItem(a))&&(a.isIgnored=!0)};j.unignore=function(a){(a=this.getItem(a))&&delete a.isIgnored};j.stamp=function(a){(a=this._find(a))&&(this.stamps=this.stamps.concat(a),a.forEach(this.ignore,this))};j.unstamp=function(b){(b=this._find(b))&&b.forEach(function(b){a.removeFrom(this.stamps,b);this.unignore(b)},this)};j._find=function(b){if(b)return"string"==typeof b&&(b=this.element.querySelectorAll(b)),
a.makeArray(b)};j._manageStamps=function(){this.stamps&&this.stamps.length&&(this._getBoundingRect(),this.stamps.forEach(this._manageStamp,this))};j._getBoundingRect=function(){var a=this.element.getBoundingClientRect(),b=this.size;this._boundingRect={left:a.left+b.paddingLeft+b.borderLeftWidth,top:a.top+b.paddingTop+b.borderTopWidth,right:a.right-(b.paddingRight+b.borderRightWidth),bottom:a.bottom-(b.paddingBottom+b.borderBottomWidth)}};j._manageStamp=k;j._getElementOffset=function(a){var b=a.getBoundingClientRect(),
d=this._boundingRect;a=h(a);return{left:b.left-d.left-a.marginLeft,top:b.top-d.top-a.marginTop,right:d.right-b.right-a.marginRight,bottom:d.bottom-b.bottom-a.marginBottom}};j.handleEvent=a.handleEvent;j.bindResize=function(){b.addEventListener("resize",this);this.isResizeBound=!0};j.unbindResize=function(){b.removeEventListener("resize",this);this.isResizeBound=!1};j.onresize=function(){this.resize()};a.debounceMethod(g,"onresize",100);j.resize=function(){this.isResizeBound&&this.needsResizeLayout()&&
this.layout()};j.needsResizeLayout=function(){var a=h(this.element);return this.size&&a&&a.innerWidth!==this.size.innerWidth};j.addItems=function(a){a=this._itemize(a);return a.length&&(this.items=this.items.concat(a)),a};j.appended=function(a){a=this.addItems(a);a.length&&(this.layoutItems(a,!0),this.reveal(a))};j.prepended=function(a){a=this._itemize(a);if(a.length){var b=this.items.slice(0);this.items=a.concat(b);this._resetLayout();this._manageStamps();this.layoutItems(a,!0);this.reveal(a);this.layoutItems(b)}};
j.reveal=function(a){if(this._emitCompleteOnItems("reveal",a),a&&a.length){var b=this.updateStagger();a.forEach(function(a,d){a.stagger(d*b);a.reveal()})}};j.hide=function(a){if(this._emitCompleteOnItems("hide",a),a&&a.length){var b=this.updateStagger();a.forEach(function(a,d){a.stagger(d*b);a.hide()})}};j.revealItemElements=function(a){a=this.getItems(a);this.reveal(a)};j.hideItemElements=function(a){a=this.getItems(a);this.hide(a)};j.getItem=function(a){for(var b=0;b<this.items.length;b++){var d=
this.items[b];if(d.element==a)return d}};j.getItems=function(b){b=a.makeArray(b);var d=[];return b.forEach(function(a){(a=this.getItem(a))&&d.push(a)},this),d};j.remove=function(b){b=this.getItems(b);this._emitCompleteOnItems("remove",b);b&&b.length&&b.forEach(function(b){b.remove();a.removeFrom(this.items,b)},this)};j.destroy=function(){var a=this.element.style;a.height="";a.position="";a.width="";this.items.forEach(function(a){a.destroy()});this.unbindResize();delete i[this.element.outlayerGUID];
delete this.element.outlayerGUID;m&&m.removeData(this.element,this.constructor.namespace)};g.data=function(b){return(b=(b=a.getQueryElement(b))&&b.outlayerGUID)&&i[b]};g.create=function(b,c){var j=e(g);return j.defaults=a.extend({},g.defaults),a.extend(j.defaults,c),j.compatOptions=a.extend({},g.compatOptions),j.namespace=b,j.data=g.data,j.Item=e(d),a.htmlInit(j,b),m&&m.bridget&&m.bridget(b,j),j};var o={ms:1,s:1E3};return g.Item=d,g});
(function(b,c){"function"==typeof define&&define.amd?define("isotope/js/item",["outlayer/outlayer"],c):"object"==typeof module&&module.exports?module.exports=c(require("outlayer")):(b.Isotope=b.Isotope||{},b.Isotope.Item=c(b.Outlayer))})(window,function(b){function c(){b.Item.apply(this,arguments)}var h=c.prototype=Object.create(b.Item.prototype),a=h._create;h._create=function(){this.id=this.layout.itemGUID++;a.call(this);this.sortData={}};h.updateSortData=function(){if(!this.isIgnored){this.sortData.id=
this.id;this.sortData["original-order"]=this.id;this.sortData.random=Math.random();var a=this.layout.options.getSortData,b=this.layout._sorters,d;for(d in a)this.sortData[d]=(0,b[d])(this.element,this)}};var d=h.destroy;return h.destroy=function(){d.apply(this,arguments);this.css({display:""})},c});
(function(b,c){"function"==typeof define&&define.amd?define("isotope/js/layout-mode",["get-size/get-size","outlayer/outlayer"],c):"object"==typeof module&&module.exports?module.exports=c(require("get-size"),require("outlayer")):(b.Isotope=b.Isotope||{},b.Isotope.LayoutMode=c(b.getSize,b.Outlayer))})(window,function(b,c){function h(a){(this.isotope=a)&&(this.options=a.options[this.namespace],this.element=a.element,this.items=a.filteredItems,this.size=a.size)}var a=h.prototype;return"_resetLayout _getItemLayoutPosition _manageStamp _getContainerSize _getElementOffset needsResizeLayout _getOption".split(" ").forEach(function(b){a[b]=
function(){return c.prototype[b].apply(this.isotope,arguments)}}),a.needsVerticalResizeLayout=function(){var a=b(this.isotope.element);return this.isotope.size&&a&&a.innerHeight!=this.isotope.size.innerHeight},a._getMeasurement=function(){this.isotope._getMeasurement.apply(this,arguments)},a.getColumnWidth=function(){this.getSegmentSize("column","Width")},a.getRowHeight=function(){this.getSegmentSize("row","Height")},a.getSegmentSize=function(a,b){var e=a+b,c="outer"+b;if(this._getMeasurement(e,c),
!this[e]){var h=this.getFirstItemSize();this[e]=h&&h[c]||this.isotope.size["inner"+b]}},a.getFirstItemSize=function(){var a=this.isotope.filteredItems[0];return a&&a.element&&b(a.element)},a.layout=function(){this.isotope.layout.apply(this.isotope,arguments)},a.getSize=function(){this.isotope.getSize();this.size=this.isotope.size},h.modes={},h.create=function(b,c){function e(){h.apply(this,arguments)}return e.prototype=Object.create(a),e.prototype.constructor=e,c&&(e.options=c),e.prototype.namespace=
b,h.modes[b]=e,e},h});
(function(b,c){"function"==typeof define&&define.amd?define("masonry/masonry",["outlayer/outlayer","get-size/get-size"],c):"object"==typeof module&&module.exports?module.exports=c(require("outlayer"),require("get-size")):b.Masonry=c(b.Outlayer,b.getSize)})(window,function(b,c){var h=b.create("masonry");h.compatOptions.fitWidth="isFitWidth";var a=h.prototype;return a._resetLayout=function(){this.getSize();this._getMeasurement("columnWidth","outerWidth");this._getMeasurement("gutter","outerWidth");
this.measureColumns();this.colYs=[];for(var a=0;a<this.cols;a++)this.colYs.push(0);this.horizontalColIndex=this.maxY=0},a.measureColumns=function(){if(this.getContainerWidth(),!this.columnWidth){var a=this.items[0];this.columnWidth=(a=a&&a.element)&&c(a).outerWidth||this.containerWidth}var a=this.columnWidth+=this.gutter,b=this.containerWidth+this.gutter,e=a-b%a,a=Math[e&&1>e?"round":"floor"](b/a);this.cols=Math.max(a,1)},a.getContainerWidth=function(){var a=this._getOption("fitWidth")?this.element.parentNode:
this.element;this.containerWidth=(a=c(a))&&a.innerWidth},a._getItemLayoutPosition=function(a){a.getSize();var b=a.size.outerWidth%this.columnWidth,e=Math[b&&1>b?"round":"ceil"](a.size.outerWidth/this.columnWidth),e=Math.min(e,this.cols),c=this[this.options.horizontalOrder?"_getHorizontalColPosition":"_getTopColPosition"](e,a),b={x:this.columnWidth*c.col,y:c.y};a=c.y+a.size.outerHeight;e+=c.col;for(c=c.col;c<e;c++)this.colYs[c]=a;return b},a._getTopColPosition=function(a){a=this._getTopColGroup(a);
var b=Math.min.apply(Math,a);return{col:a.indexOf(b),y:b}},a._getTopColGroup=function(a){if(2>a)return this.colYs;for(var b=[],e=this.cols+1-a,c=0;c<e;c++)b[c]=this._getColGroupY(c,a);return b},a._getColGroupY=function(a,b){if(2>b)return this.colYs[a];var e=this.colYs.slice(a,a+b);return Math.max.apply(Math,e)},a._getHorizontalColPosition=function(a,b){var e=this.horizontalColIndex%this.cols,e=1<a&&e+a>this.cols?0:e;return this.horizontalColIndex=b.size.outerWidth&&b.size.outerHeight?e+a:this.horizontalColIndex,
{col:e,y:this._getColGroupY(e,a)}},a._manageStamp=function(a){var b=c(a),e=this._getElementOffset(a);a=this._getOption("originLeft")?e.left:e.right;var f=a+b.outerWidth,h=Math.floor(a/this.columnWidth),h=Math.max(0,h);a=Math.floor(f/this.columnWidth);a-=f%this.columnWidth?0:1;a=Math.min(this.cols-1,a);b=(this._getOption("originTop")?e.top:e.bottom)+b.outerHeight;for(e=h;e<=a;e++)this.colYs[e]=Math.max(b,this.colYs[e])},a._getContainerSize=function(){this.maxY=Math.max.apply(Math,this.colYs);var a=
{height:this.maxY};return this._getOption("fitWidth")&&(a.width=this._getContainerFitWidth()),a},a._getContainerFitWidth=function(){for(var a=0,b=this.cols;--b&&0===this.colYs[b];)a++;return(this.cols-a)*this.columnWidth-this.gutter},a.needsResizeLayout=function(){var a=this.containerWidth;return this.getContainerWidth(),a!=this.containerWidth},h});
(function(b,c){"function"==typeof define&&define.amd?define("isotope/js/layout-modes/masonry",["../layout-mode","masonry/masonry"],c):"object"==typeof module&&module.exports?module.exports=c(require("../layout-mode"),require("masonry-layout")):c(b.Isotope.LayoutMode,b.Masonry)})(window,function(b,c){var h=b.create("masonry"),a=h.prototype,d={_getElementOffset:!0,layout:!0,_getMeasurement:!0},g;for(g in c.prototype)d[g]||(a[g]=c.prototype[g]);var e=a.measureColumns;a.measureColumns=function(){this.items=
this.isotope.filteredItems;e.call(this)};var f=a._getOption;return a._getOption=function(a){return"fitWidth"==a?void 0!==this.options.isFitWidth?this.options.isFitWidth:this.options.fitWidth:f.apply(this.isotope,arguments)},h});
(function(b,c){"function"==typeof define&&define.amd?define("isotope/js/layout-modes/fit-rows",["../layout-mode"],c):"object"==typeof exports?module.exports=c(require("../layout-mode")):c(b.Isotope.LayoutMode)})(window,function(b){b=b.create("fitRows");var c=b.prototype;return c._resetLayout=function(){this.maxY=this.y=this.x=0;this._getMeasurement("gutter","outerWidth")},c._getItemLayoutPosition=function(b){b.getSize();var a=b.size.outerWidth+this.gutter,d=this.isotope.size.innerWidth+this.gutter;
0!==this.x&&a+this.x>d&&(this.x=0,this.y=this.maxY);d={x:this.x,y:this.y};return this.maxY=Math.max(this.maxY,this.y+b.size.outerHeight),this.x+=a,d},c._getContainerSize=function(){return{height:this.maxY}},b});
(function(b,c){"function"==typeof define&&define.amd?define("isotope/js/layout-modes/vertical",["../layout-mode"],c):"object"==typeof module&&module.exports?module.exports=c(require("../layout-mode")):c(b.Isotope.LayoutMode)})(window,function(b){b=b.create("vertical",{horizontalAlignment:0});var c=b.prototype;return c._resetLayout=function(){this.y=0},c._getItemLayoutPosition=function(b){b.getSize();var a=(this.isotope.size.innerWidth-b.size.outerWidth)*this.options.horizontalAlignment,d=this.y;return this.y+=
b.size.outerHeight,{x:a,y:d}},c._getContainerSize=function(){return{height:this.y}},b});
(function(b,c){"function"==typeof define&&define.amd?define("outlayer/outlayer get-size/get-size desandro-matches-selector/matches-selector fizzy-ui-utils/utils isotope/js/item isotope/js/layout-mode isotope/js/layout-modes/masonry isotope/js/layout-modes/fit-rows isotope/js/layout-modes/vertical".split(" "),function(h,a,d,g,e,f){return c(b,h,a,d,g,e,f)}):"object"==typeof module&&module.exports?module.exports=c(b,require("outlayer"),require("get-size"),require("desandro-matches-selector"),require("fizzy-ui-utils"),
require("isotope/js/item"),require("isotope/js/layout-mode"),require("isotope/js/layout-modes/masonry"),require("isotope/js/layout-modes/fit-rows"),require("isotope/js/layout-modes/vertical")):b.Isotope=c(b,b.Outlayer,b.getSize,b.matchesSelector,b.fizzyUIUtils,b.Isotope.Item,b.Isotope.LayoutMode)})(window,function(b,c,h,a,d,g,e){var f=b.jQuery,m=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")},k=c.create("isotope",{layoutMode:"masonry",isJQueryFiltering:!0,
sortAscending:!0});k.Item=g;k.LayoutMode=e;b=k.prototype;b._create=function(){this.itemGUID=0;this._sorters={};this._getSorters();c.prototype._create.call(this);this.modes={};this.filteredItems=this.items;this.sortHistory=["original-order"];for(var a in e.modes)this._initLayoutMode(a)};b.reloadItems=function(){this.itemGUID=0;c.prototype.reloadItems.call(this)};b._itemize=function(){for(var a=c.prototype._itemize.apply(this,arguments),b=0;b<a.length;b++)a[b].id=this.itemGUID++;return this._updateItemsSortData(a),
a};b._initLayoutMode=function(a){var b=e.modes[a],c=this.options[a]||{};this.options[a]=b.options?d.extend(b.options,c):c;this.modes[a]=new b(this)};b.layout=function(){return!this._isLayoutInited&&this._getOption("initLayout")?void this.arrange():void this._layout()};b._layout=function(){var a=this._getIsInstant();this._resetLayout();this._manageStamps();this.layoutItems(this.filteredItems,a);this._isLayoutInited=!0};b.arrange=function(a){this.option(a);this._getIsInstant();a=this._filter(this.items);
this.filteredItems=a.matches;this._bindArrangeComplete();this._isInstant?this._noTransition(this._hideReveal,[a]):this._hideReveal(a);this._sort();this._layout()};b._init=b.arrange;b._hideReveal=function(a){this.reveal(a.needReveal);this.hide(a.needHide)};b._getIsInstant=function(){var a=this._getOption("layoutInstant"),a=void 0!==a?a:!this._isLayoutInited;return this._isInstant=a,a};b._bindArrangeComplete=function(){function a(){b&&d&&e&&c.dispatchEvent("arrangeComplete",null,[c.filteredItems])}
var b,d,e,c=this;this.once("layoutComplete",function(){b=!0;a()});this.once("hideComplete",function(){d=!0;a()});this.once("revealComplete",function(){e=!0;a()})};b._filter=function(a){for(var b=this.options.filter,d=[],e=[],c=[],b=this._getFilterTest(b||"*"),f=0;f<a.length;f++){var g=a[f];if(!g.isIgnored){var h=b(g);h&&d.push(g);h&&g.isHidden?e.push(g):h||g.isHidden||c.push(g)}}return{matches:d,needReveal:e,needHide:c}};b._getFilterTest=function(b){return f&&this.options.isJQueryFiltering?function(a){return f(a.element).is(b)}:
"function"==typeof b?function(a){return b(a.element)}:function(d){return a(d.element,b)}};b.updateSortData=function(a){var b;a?(a=d.makeArray(a),b=this.getItems(a)):b=this.items;this._getSorters();this._updateItemsSortData(b)};b._getSorters=function(){var a=this.options.getSortData,b;for(b in a)this._sorters[b]=l(a[b])};b._updateItemsSortData=function(a){for(var b=a&&a.length,d=0;b&&d<b;d++)a[d].updateSortData()};var l;l=function(a){if("string"!=typeof a)return a;a=m(a).split(" ");var b=a[0],d=b.match(/^\[(.+)\]$/),
e,c=d&&d[1];e=c?function(a){return a.getAttribute(c)}:function(a){return(a=a.querySelector(b))&&a.textContent};var f=k.sortDataParsers[a[1]];return a=f?function(a){return a&&f(e(a))}:function(a){return a&&e(a)}};k.sortDataParsers={parseInt:function(a){return parseInt(a,10)},parseFloat:function(a){return parseFloat(a)}};b._sort=function(){if(this.options.sortBy){var a=d.makeArray(this.options.sortBy);this._getIsSameSortBy(a)||(this.sortHistory=a.concat(this.sortHistory));var b=this.sortHistory,e=this.options.sortAscending;
this.filteredItems.sort(function(a,d){for(var c=0;c<b.length;c++){var f=b[c],j=a.sortData[f],g=d.sortData[f];if(j>g||j<g)return(j>g?1:-1)*((void 0!==e[f]?e[f]:e)?1:-1)}return 0})}};b._getIsSameSortBy=function(a){for(var b=0;b<a.length;b++)if(a[b]!=this.sortHistory[b])return!1;return!0};b._mode=function(){var a=this.options.layoutMode,b=this.modes[a];if(!b)throw Error("No layout mode: "+a);return b.options=this.options[a],b};b._resetLayout=function(){c.prototype._resetLayout.call(this);this._mode()._resetLayout()};
b._getItemLayoutPosition=function(a){return this._mode()._getItemLayoutPosition(a)};b._manageStamp=function(a){this._mode()._manageStamp(a)};b._getContainerSize=function(){return this._mode()._getContainerSize()};b.needsResizeLayout=function(){return this._mode().needsResizeLayout()};b.appended=function(a){a=this.addItems(a);a.length&&(a=this._filterRevealAdded(a),this.filteredItems=this.filteredItems.concat(a))};b.prepended=function(a){a=this._itemize(a);if(a.length){this._resetLayout();this._manageStamps();
var b=this._filterRevealAdded(a);this.layoutItems(this.filteredItems);this.filteredItems=b.concat(this.filteredItems);this.items=a.concat(this.items)}};b._filterRevealAdded=function(a){a=this._filter(a);return this.hide(a.needHide),this.reveal(a.matches),this.layoutItems(a.matches,!0),a.matches};b.insert=function(a){a=this.addItems(a);if(a.length){var b,d,e=a.length;for(b=0;b<e;b++)d=a[b],this.element.appendChild(d.element);d=this._filter(a).matches;for(b=0;b<e;b++)a[b].isLayoutInstant=!0;this.arrange();
for(b=0;b<e;b++)delete a[b].isLayoutInstant;this.reveal(d)}};var i=b.remove;return b.remove=function(a){a=d.makeArray(a);var b=this.getItems(a);i.call(this,a);a=b&&b.length;for(var e=0;a&&e<a;e++)d.removeFrom(this.filteredItems,b[e])},b.shuffle=function(){for(var a=0;a<this.items.length;a++)this.items[a].sortData.random=Math.random();this.options.sortBy="random";this._sort();this._layout()},b._noTransition=function(a,b){var d=this.options.transitionDuration;this.options.transitionDuration=0;var e=
a.apply(this,b);return this.options.transitionDuration=d,e},b.getFilteredItemElements=function(){return this.filteredItems.map(function(a){return a.element})},k});
(function(b){b.fn.theiaStickySidebar=function(c){function h(d,c){if(!0===d.initialized)return!0;if(b("body").width()<d.minWidth)return!1;d.initialized=!0;0===b("#theia-sticky-sidebar-stylesheet-"+d.namespace).length&&b("head").append(b('\x3cstyle id\x3d"theia-sticky-sidebar-stylesheet-'+d.namespace+'"\x3e.theiaStickySidebar:after {content: ""; display: table; clear: both;}\x3c/style\x3e'));c.each(function(){function e(){c.fixedScrollTop=0;c.sidebar.css({"min-height":"1px"});c.stickySidebar.css({position:"static",
width:"",transform:"none"})}var c={};c.sidebar=b(this);c.options=d||{};c.container=b(c.options.containerSelector);0==c.container.length&&(c.container=c.sidebar.parent());c.sidebar.parents().css("-webkit-transform","none");c.sidebar.css({position:c.options.defaultPosition,overflow:"visible","-webkit-box-sizing":"border-box","-moz-box-sizing":"border-box","box-sizing":"border-box"});c.stickySidebar=c.sidebar.find(".theiaStickySidebar");if(0==c.stickySidebar.length){var g=/(?:text|application)\/(?:x-)?(?:javascript|ecmascript)/i;
c.sidebar.find("script").filter(function(a,b){return 0===b.type.length||b.type.match(g)}).remove();c.stickySidebar=b("\x3cdiv\x3e").addClass("theiaStickySidebar").append(c.sidebar.children());c.sidebar.append(c.stickySidebar)}c.marginBottom=parseInt(c.sidebar.css("margin-bottom"));c.paddingTop=parseInt(c.sidebar.css("padding-top"));c.paddingBottom=parseInt(c.sidebar.css("padding-bottom"));var h=c.stickySidebar.offset().top,l=c.stickySidebar.outerHeight();c.stickySidebar.css("padding-top",1);c.stickySidebar.css("padding-bottom",
1);h-=c.stickySidebar.offset().top;l=c.stickySidebar.outerHeight()-l-h;0==h?(c.stickySidebar.css("padding-top",0),c.stickySidebarPaddingTop=0):c.stickySidebarPaddingTop=1;0==l?(c.stickySidebar.css("padding-bottom",0),c.stickySidebarPaddingBottom=0):c.stickySidebarPaddingBottom=1;c.previousScrollTop=null;c.fixedScrollTop=0;e();c.onScroll=function(c){if(c.stickySidebar.is(":visible"))if(b("body").width()<c.options.minWidth)e();else if(c.options.disableOnResponsiveLayouts&&c.sidebar.outerWidth("none"==
c.sidebar.css("float"))+50>c.container.width())e();else{var g=b(document).scrollTop(),f="static";if(g>=c.sidebar.offset().top+(c.paddingTop-c.options.additionalMarginTop)){var h=c.paddingTop+d.additionalMarginTop,i=c.paddingBottom+c.marginBottom+d.additionalMarginBottom,k=c.sidebar.offset().top,f=c.sidebar.offset().top,l=c.container,m=l.height();l.children().each(function(){m=Math.max(m,b(this).height())});var l=f+m,f=0+d.additionalMarginTop,h=c.stickySidebar.outerHeight()+h+i<b(window).height()?
f+c.stickySidebar.outerHeight():b(window).height()-c.marginBottom-c.paddingBottom-d.additionalMarginBottom,i=k-g+c.paddingTop,l=l-g-c.paddingBottom-c.marginBottom,k=c.stickySidebar.offset().top-g,s=c.previousScrollTop-g;"fixed"==c.stickySidebar.css("position")&&"modern"==c.options.sidebarBehavior&&(k+=s);"stick-to-top"==c.options.sidebarBehavior&&(k=d.additionalMarginTop);"stick-to-bottom"==c.options.sidebarBehavior&&(k=h-c.stickySidebar.outerHeight());k=0<s?Math.min(k,f):Math.max(k,h-c.stickySidebar.outerHeight());
k=Math.max(k,i);k=Math.min(k,l-c.stickySidebar.outerHeight());i=c.container.height()==c.stickySidebar.outerHeight();f=!i&&k==f?"fixed":!i&&k==h-c.stickySidebar.outerHeight()?"fixed":g+k-c.sidebar.offset().top-c.paddingTop<=d.additionalMarginTop?"static":"absolute"}"fixed"==f?(h=b(document).scrollLeft(),c.stickySidebar.css({position:"fixed",width:a(c.stickySidebar)+"px",transform:"translateY("+k+"px)",left:c.sidebar.offset().left+parseInt(c.sidebar.css("padding-left"))-h+"px",top:"0px"})):"absolute"==
f?(h={},"absolute"!=c.stickySidebar.css("position")&&(h.position="absolute",h.transform="translateY("+(g+k-c.sidebar.offset().top-c.stickySidebarPaddingTop-c.stickySidebarPaddingBottom)+"px)",h.top="0px"),h.width=a(c.stickySidebar)+"px",h.left="",c.stickySidebar.css(h)):"static"==f&&e();"static"!=f&&!0==c.options.updateSidebarHeight&&c.sidebar.css({"min-height":c.stickySidebar.outerHeight()+c.stickySidebar.offset().top-c.sidebar.offset().top+c.paddingBottom});c.previousScrollTop=g}};c.onScroll(c);
b(document).on("scroll."+c.options.namespace,function(a){return function(){a.onScroll(a)}}(c));b(window).on("resize."+c.options.namespace,function(a){return function(){a.stickySidebar.css({position:"static"});a.onScroll(a)}}(c));if("undefined"!==typeof ResizeSensor){var i=c;new ResizeSensor(c.stickySidebar[0],function(){i.onScroll(i)})}});return!0}function a(a){var b;try{b=a[0].getBoundingClientRect().width}catch(c){}"undefined"===typeof b&&(b=a.width());return b}c=b.extend({containerSelector:"",
additionalMarginTop:0,additionalMarginBottom:0,updateSidebarHeight:!0,minWidth:0,disableOnResponsiveLayouts:!0,sidebarBehavior:"modern",defaultPosition:"relative",namespace:"TSS"},c);c.additionalMarginTop=parseInt(c.additionalMarginTop)||0;c.additionalMarginBottom=parseInt(c.additionalMarginBottom)||0;h(c,this)||(console.log("TSS: Body width smaller than options.minWidth. Init is delayed."),b(document).on("scroll."+c.namespace,function(a,c){return function(e){h(a,c)&&b(this).unbind(e)}}(c,this)),
b(window).on("resize."+c.namespace,function(a,c){return function(e){h(a,c)&&b(this).unbind(e)}}(c,this)));return this}})(jQuery);